// スタイル

exports.style = {

// common -------------------------------------------------------	
	commonSize:{
		// 計算で遣う数値なので'dp'はつけない
		screenWidth: Ti.Platform.displayCaps.platformWidth,
		screenHeight: Ti.Platform.displayCaps.platformHeight,
	},

	commonActivityIndicator:{
//		backgroundColor: 'black',
		opacity: 0.7,
		width: '100%',
		height: '100%',
		style: Ti.UI.iPhone.ActivityIndicatorStyle.DARK,
		font: {fontSize:14, fontWeight:'bold'},
		color: 'gray',
		message: 'Loading...',
	},

	commonTableHeader:{
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: '60dp',
//		backgroundColor: '#dedede',
	},	    
	commonHeaderBorder:{
	    bottom: '0dp',
		height: '0dp',
	},	    
	commonUpdateArrowImage:{
	    left: '20dp',
	    bottom: '10dp',
	    width: '23dp',
	    height: '60dp',
		defaultImage: '',
	    image:'images/whiteArrow.png',
	},
	commonPullLabel:{
	    left: '55dp', 
	    bottom: '30dp',
	    width: '200dp',
	    color:'white',
	    font: {fontSize:13, fontWeight:'bold'},
	    text: 'Pull down to refresh...',
	    textAlign: 'center',
	},
	commonLastUpdatedLabel:{
	    left: '55dp',
	    bottom: '15dp',
	    width: '200dp',
	    color: 'white',
	    font: {fontSize:12},
	    textAlign: 'center',
	},
	commonUpdateIndicator:{
	    left: '20dp',
	    bottom: '13dp',
	    width: '30dp',
	    height: '30dp',
	    image:'images/whiteArrow.png',
	    left: '20dp',
	    bottom: '10dp',
	    width: '23dp',
	    height: '60dp',
	},
	
	commonBackButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_arrow_left.png',
	},
	commonNextButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_arrow_right.png',
	},
	commonPlusButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_plus.png',
	},
	
// tab -------------------------------------------------------
	tabGroupHidden:{
		// カスタムプロパティ
	},
	tabHidden:{
		// カスタムプロパティ
	},
	tabGroupView:{
		layout: 'horizontal',
		// ステータスバー(20)＋タイトルバー(44)が座標の開始位置なので、その分とタブバーの高さを引く
//		top: (Ti.Platform.displayCaps.platformHeight - 108) + 'dp',
		bottom: '0dp',
		left: '0dp',
		width: '100%',
		height: '44dp',
//		backgroundColor: '#E87C8C',
		backgroundColor: '#e74c3c',
//		backgroundColor: '#d86853',
//		backgroundColor: '#48a59b',
//		backgroundColor: '#676769',
//		backgroundColor: '#ed9764',
//		backgroundColor: '#423737',
//		backgroundColor: '#6ea1c9',
//		backgroundColor: '#c67267',
//		backgroundColor: '#63768a',
//		backgroundColor: '#61594e',
	},
	tabView:{
//		layout: 'vertical',
		top: '0dp',
		left: '0dp',
		width: '80dp',
		height: '44dp',
		// カスタムプロパティ
		objectName: null,
	},
	tabImage:{
//		top: '3dp',
//		width: '28dp',
		height: '28dp',
		defaultImage: '',
		bubbleParent: true,
		// カスタムプロパティ
		tabIndex: null,
	},
	tabLabel:{
		top: '1dp',
		width: '60dp',
		height: '10dp',
		textAlign: 'center',
		font: {fontSize:10, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: 'white',
	},

// winLogin -------------------------------------------------------
	loginWin:{
		backgroundColor: 'white',
		// カスタムプロパティ
		objectName : 'loginWin',
	},

	loginFacebookButton:{
		top : '100dp',
	},

// winPhoto -------------------------------------------------------
	photoWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		title: 'フォト',
		// カスタムプロパティ
		objectName : 'photoWin',
		prevWin : null,
	},

	photoTitleView:{
		layout: 'absolute',
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},
	photoTitleIconView:{
		left: '0dp',
		width: '28dp',
		height: '28dp',
		borderRadius: '14dp',
		backgroundColor: 'white',
	},
	photoTitleIconImage:{
		width: '28dp',
		height: '28dp',
		defaultImage: '',
		touchEnabled: false,
	},
	photoTitleNameView:{
		layout: 'vertical',
		top: '3dp',
		left: '33dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	photoTitleNameLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: 'white',
	},
	photoTitleUserLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: 'white',
	},

	photoTableView:{ 
		// 下のタブで表示されない余白分
		bottom: '44dp',
		backgroundColor: 'white',
		separatorColor: 'transparent',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		data: [],
	},
	photoArticleTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		touchEnabled: false,
	},

	photoArticleView:{
		layout: 'vertical',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
	},
	photoPhotoView:{
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: (Ti.Platform.displayCaps.platformWidth * 3 / 4) + 'dp',
		backgroundColor: 'white',
	},
	photoPhotoImage:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
		backgroundColor: 'black',
		// カスタムプロパティ
		articleData: null,
	},
	photoArticleTextView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '1dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	photoTextView:{
		layout: 'vertical',
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		right: '10dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},
	photoNameLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoTextLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoTimeLabel:{
		top: '5dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	photoLikeStampImage:{
		top: '5dp',
		bottom: '5dp',
		right: '10dp',
		width: '54dp',
		height: '54dp',
		defaultImage: '',
		image: 'images/icon/b_like_before.png',
		touchEnabled: false,
		visible: false,
		// カスタムプロパティ
		clickFlag: false,
	},

	photoActionView:{
		layout: 'horizontal',
		top: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	photoCommentActionView:{
		layout: 'horizontal',
		top: '0dp',
//		right: '1dp',
		width: '120dp',
		height: Ti.UI.SIZE,
		backgroundColor: '#f5f5f5',
	},
	photoCommentActionImage:{
		top: '5dp',
		bottom: '5dp',
		left: '5dp',
		width: '28dp',
		height: '28dp',
		defaultImage: '',
		image: 'images/icon/b_comment_square.png',
	},
	photoCommentActionLabel:{
		top: '5dp',
		bottom: '5dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: '28dp',
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: 'コメントする',
	},
	photoShareActionView:{
		layout: 'horizontal',
		top: '0dp',
//		right: '1dp',
		width: '199dp',
		height: Ti.UI.SIZE,
		backgroundColor: '#f5f5f5',
	},
	photoShareActionImage:{
		top: '5dp',
		bottom: '5dp',
		left: '5dp',
		width: '28dp',
		height: '28dp',
		defaultImage: '',
		image: 'images/icon/b_arrow.png',
	},
	photoShareActionLabel:{
		top: '5dp',
		bottom: '5dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: '28dp',
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: 'シェアする',
	},

	photoCommentTableRow:{ 
		top: '0dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	photoCommentListView:{
		layout: 'vertical',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
	},
	photoCommentView:{
		layout: 'horizontal',
		top: '0dp',
	    bottom: '1dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	photoCommentUserIconView:{
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		width: '36dp',
		height: '36dp',
		borderRadius: '18dp',
	},
	photoCommentUserIconImage:{
		width: '36dp',
		height: '36dp',
		defaultImage: '',
	},
	photoCommentTextView:{
		layout: 'vertical',
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		right: '10dp',
		// photoCommentUserIconImage(10+36)と余白（10+10）を除いたサイズ
		width: (Ti.Platform.displayCaps.platformWidth - 66) + 'dp',
		height: Ti.UI.SIZE,
	},
	photoCommentNameLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoCommentTextLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoCommentTimeLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

	photoCommentField:{
		top: '0dp',
		width: '255dp',
		height: '30dp',
		backgroundColor: 'white',
		borderColor:'#dedede',
		borderRadius: '0',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		hintText: 'comment',
		keyboardToolbarColor: '#f5f5f5',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_SEND,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_ROUNDED,
	},
	photoCommentPostButton:{
		width: '32dp',
		height: '28dp',
		backgroundImage: 'images/icon/titlebar.png',
	},
	photoCommentPostImage:{
		width: '18dp',
		height: '18dp',
		defaultImage: '',
		image:'images/icon/w_plus.png',
	},

	photoPhotoFullWin:{
		backgroundColor: 'black',
		tabBarHidden: true,
	},
	photoPhotoFullImage:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
		backgroundColor: 'black',
	},

// winProfile -------------------------------------------------------
	profileWin:{
		backgroundColor: '#dedede',
//		barColor: '#e74c3c',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		title: 'プロフィール',
		// カスタムプロパティ
		objectName : 'profileWin',
	},

	profileTitleView:{
		layout: 'horizontal',
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},
	profileTitleLabel:{
		left: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'プロフィール', 
	},

	profileFollowButton:{
		width: '95dp',
		height: '25dp',
//		backgroundColor: '#dedede',
		backgroundImage: 'images/icon/titlebar10.png',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		// ヘッダのボタンのテキストの色が反映できない
		color: '#e74c3c',
		title: 'フォローする',
	},
	profileUnfollowButton:{
		width: '95dp',
		height: '25dp',
//		backgroundColor: '#dedede',
		backgroundImage: 'images/icon/titlebar10.png',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#e74c3c',
		title: 'フォロー中',
	},
	profileEditButton:{
		left: '0dp',
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_profile_edit.png',
	},
	profileConfigButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_profile_gear.png',
	},

	profileTableView:{ 
		top: '0dp',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		width: '100%',
		height: Ti.UI.SIZE,
//		backgroundColor: 'white',
//		scrollable: false,
		data: [],
	},

	profileCountTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	profileIconView:{
		top: '8dp',
		bottom: '8dp',
		left: '13dp',
		right: '10dp',
		width: '54dp',
		height: '54dp',
		borderRadius: '27dp',
	},
	profileIconImage:{
		width: '54dp',
		height: '54dp',
		defaultImage: '',
	},
	profileCountView:{
		layout: 'horizontal',
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	profileCountDataView:{
		layout: 'vertical',
		top: '10dp',
		right: '1dp',
		width: '79dp',
		height: '46dp',
	},
	profileCountDataLabel:{
		top: '5dp',
		textAlign: 'center',
		font: {fontSize:16, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	profileCountDataUnitLabel:{
		top: '1dp',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},

	profileInfoTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	profileInfoView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '10dp',
		left: '15dp',
		right: '15dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	profileInfoNameView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '5dp',
		left: '0dp',
		height: Ti.UI.SIZE,
	},
	profileInfoNameLabel:{
		top: '0dp',
		left: '0dp',
		right: '5dp',
		width: Ti.UI.SIZE,
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	profileInfoUserLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	profileInfoBreedLabel:{
		top: '0dp',
		left: '0dp',
		height: Ti.UI.SIZE,
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	profileInfoBirthLabel:{
		top: '0dp',
		bottom: '5dp',
		left: '0dp',
		height: Ti.UI.SIZE,
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	profileInfoMemoLabel:{
		top: '0dp',
		left: '0dp',
		height: Ti.UI.SIZE,
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},

	profilePhotoTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	profilePhotoView:{
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: (Ti.Platform.displayCaps.platformWidth * 3 / 4) + 'dp',
		backgroundColor: 'white',
	},
	profilePhotoImage:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
	},

// winProfileEdit -------------------------------------------------------
	profileEditWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		title: 'プロフィール',
		// カスタムプロパティ
		objectName : 'profileEditWin',
	},

	profileEditTitleView:{
		layout: 'absolute',
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},
	profileEditTitleLabel:{
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969',
		highlightedColor: '#696969',
		text: 'プロフィール', 
	},
	profileSaveButton:{
//		width: '28dp',
//		height: '28dp',
//		backgroundImage:'images/icon/w_profile_save.png',
		width: '50dp',
		height: '25dp',
//		backgroundColor: '#dedede',
		backgroundImage: 'images/icon/titlebar10.png',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#e74c3c',
		title: '保存',
	},

	profileEditTableView:{ 
		top: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
//		scrollable: false,
		data: [],
	},
	profileEditListTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		selectedBackgroundColor: 'white',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		// カスタムプロパティ
		objectName: null,
	},
	profileEditListTitleView:{
		layout: 'absolute',
		top: '0dp',
		height: '30dp',
		backgroundColor: '#eeeeee',
	},
	profileEditListTitleLabel:{
		left: '15dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	profileEditListItemView:{
		layout: 'absolute',
		top: '0dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	profileEditListItemLabel:{
		top: '0dp',
		left: '15dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	profileEditListValueLabel:{
		right: '15dp',
		textAlign:'right',
		width: '166dp',
		height: '35dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	profileEditListValueField:{
		top: '0dp',
		right: '15dp',
		textAlign:'right',
		width: '166dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
        touchEnabled: true,
	},
	profileEditListTextArea:{
		top : '30dp',
		bottom : '10dp',
		left: '7dp',
		width: '306dp',
		height : '90dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
		// hintTextはiOSで対応されていないので、focus/blur時に処理
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        touchEnabled: true,
	},

	profileEditListPickerView:{
		bottom: '-259dp',
		height: '259dp',
	},
	profileEditListPickerToolbar:{
		top: '0dp',
		items: null,
	},
	profileEditListCancelButton:{
		style: Ti.UI.iPhone.SystemButtonStyle.BORDERED,
		title: 'Cancel',
	},
	profileEditListSpacerButton:{
		systemButton:Ti.UI.iPhone.SystemButton.FLEXIBLE_SPACE,
	},
	profileEditListDoneButton:{
		style:Ti.UI.iPhone.SystemButtonStyle.DONE,
		title: 'Done',
	},
	profileEditListPicker:{
		top: '43dp',
		selectionIndicator: true,
	},
	profileEditListDatePicker:{
		top: '43dp',
		selectionIndicator: true,
		type:Ti.UI.PICKER_TYPE_DATE,
		minDate:new Date(1980,1,1),
		maxDate:new Date(2020,12,31),
		value: null,
	},

// winProfileConfig -------------------------------------------------------
	profileConfigWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		title: '設定',
		// カスタムプロパティ
		objectName : 'profileConfigWin',
	},

	profileConfigTitleView:{
		layout: 'absolute',
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},
	profileConfigTitleLabel:{
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: '設定', 
	},

	profileConfigTableView:{ 
		top: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
//		scrollable: false,
		data: [],
	},
	profileConfigListTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		selectedBackgroundColor: 'white',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		// カスタムプロパティ
		objectName: null,
	},
	profileConfigListTitleView:{
		layout: 'absolute',
		top: '0dp',
		height: '30dp',
		backgroundColor: '#eeeeee',
	},
	profileConfigListTitleLabel:{
		left: '15dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	profileConfigListItemView:{
		layout: 'absolute',
		top: '0dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	profileConfigListValueField:{
		top: '0dp',
		right: '15dp',
		textAlign:'right',
		width: '166dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
        touchEnabled: false,
	},
	profileConfigListItemLabel:{
		top: '0dp',
		left: '15dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	profileConfigListPickerView:{
		bottom: '-259dp',
		height: '259dp',
	},
	profileConfigListPickerToolbar:{
		top: '0dp',
		items: null,
	},
	profileConfigListCancelButton:{
		style: Ti.UI.iPhone.SystemButtonStyle.BORDERED,
		title: 'Cancel',
	},
	profileConfigListSpacerButton:{
		systemButton:Ti.UI.iPhone.SystemButton.FLEXIBLE_SPACE,
	},
	profileConfigListDoneButton:{
		style:Ti.UI.iPhone.SystemButtonStyle.DONE,
		title: 'Done',
	},
	profileConfigListHourPicker:{
		top: '43dp',
		selectionIndicator: true,
		type:Ti.UI.PICKER_TYPE_PLAIN,
		value: null,
	},

	
// winPhotoList -------------------------------------------------------
	photoListWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'photoListWin',
	},

	photoListTitleView:{
		layout: 'absolute',
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},

	photoListUpdateButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		title: '更新する',
	},

	photoListTodayTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: '今日のわんこ', 
	},

	photoListFirendsTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'わんとも', 
	},

	photoListPhotoTitleLabel:{
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'フォト', 
	},

	photoListLikeTitleLabel:{
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'わんポチ', 
	},

	photoListTableView:{ 
		// 下のタブで表示されない余白分
		bottom: '44dp',
		backgroundColor: 'white',
		separatorColor: 'transparent',
		data: [],
	},
	photoListArticleTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	photoListNextTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},

	photoListArticleListView:{
		layout: 'horizontal',
		top: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: Ti.UI.SIZE,
	},
	photoListArticleView:{
		layout: 'vertical',
		top: '5dp',
		left: '5dp',
//		width: '100dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		width: '106dp',
//		height: (106 * 3 / 4) + 'dp',
		backgroundColor: 'white',
	},
	photoListPhotoImage:{
//		top: '5dp',
		top: '0dp',
//		width: '90dp',
//		height: '90dp',
		width: '100dp',
		height: (100 * 3 / 4) + 'dp',
		defaultImage: '',
		backgroundColor: 'white',
		// カスタムプロパティ
		articleData: null,
	},
	photoListTextLabel:{
		top: '3dp',
	    bottom: '3dp',
		width: '90dp',
		height: '15dp',
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoListPhotoFullWin:{
		backgroundColor: 'black',
		tabBarHidden: true,
	},
	photoListPhotoFullImage:{
//		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
	},

	photoListFriendsArticleListView:{
		layout: 'horizontal',
		top: '0dp',
		width: '280dp',
		height: Ti.UI.SIZE,
	},
	photoListFriendsArticleView:{
		layout: 'vertical',
		top: '5dp',
		left: '10dp',
		width: '125dp',
//		height: '176dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	photoListFriendsPhotoImage:{
		top: '6dp',
		width: '113dp',
		height: '113dp',
		defaultImage: '',
		backgroundColor: 'black',
		// カスタムプロパティ
		articleData: null,
	},
	photoListFriendsNameLabel:{
		top: '3dp',
		width: '105dp',
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoListFriendsTextLabel:{
		top: '0dp',
		width: '105dp',
		height: '18dp',
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoListFriendsCountView:{
		layout: 'horizontal',
		top: '0dp',
	    bottom: '3dp',
		width: '105dp',
		height: Ti.UI.SIZE,
	},
	photoListFriendsLikeIconImage:{
		left: '0dp',
		width: '18dp',
		height: '18dp',
		defaultImage: '',
		image: 'images/icon/like.gif',
	},
	photoListFriendsLikeLabel:{
		left: '6dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoListFriendsCommentIconImage:{
		left: '12dp',
		width: '15dp',
		height: '15dp',
		defaultImage: '',
		image: 'images/icon/light_comment.png',
	},
	photoListFriendsCommentLabel:{
		left: '8dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},

	photoListNextView:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: '40dp',
		backgroundColor: '#dedede',
	},
	photoListNextButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		title: '続きを読む',
	},
	photoListNoDataLabel:{
		top: '5dp',
		width: '90dp',
		height: '15dp',
		backgroundColor: '#dedede',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: 'データがありません'
	},

// winUserList -------------------------------------------------------
	userListWin:{
		layout: 'vertical',
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'userListWin',
		prevWin : null,
	},

	userListTitleView:{
		layout: 'absolute',
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},
	userListTitleLabel:{
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},

	userListTableView:{ 
		top: '0dp',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		backgroundColor: 'white',
		separatorColor: 'transparent',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		data: [],
	},
	userListUserTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		touchEnabled: false,
	},
	userListNextTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		touchEnabled: false,
	},
	userListUserListView:{
		layout: 'vertical',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	userListUserView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '1dp',
//		width: '284dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	userListIconView:{
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		width: '54dp',
		height: '54dp',
		borderRadius: '27dp',
		// カスタムプロパティ
		userData: null,
	},
	userListIconImage:{
		width: '54dp',
		height: '54dp',
		defaultImage: '',
		touchEnabled: false,
	},
	userListTextLabel:{
		top: '10dp',
		left: '10dp',
		width: '140dp',
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	userListNextView:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: '40dp',
		backgroundColor: '#dedede',
	},
	userListNextButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		title: '続きを読む',
	},

	userListNoDataTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	userListNoDataView:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: '100%',
	},
	userListNoDataLabel:{
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: '検索結果はありませんでした'
	},

	userFollowButton:{
		right: '10dp',
		width: '95dp',
		height: '25dp',
		style: Ti.UI.iPhone.SystemButtonStyle.PLAIN,
		borderColor: '#dedede',
		borderWidth: 1,
//		borderRadius: 5,
		// カスタムプロパティ
		user: null,
		clickFlag: false,
	},
	userFollowButtonLabel:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: 'フォローする',
	},
	userListSearchTableView:{ 
		top: '0dp',
		bottom: '1dp',
		height: Ti.UI.SIZE,
		separatorColor: 'transparent',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		data: [],
	},
	userListSearchTableRow:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		touchEnabled: false,
	},
	userListSearchView:{
		top: '0dp',
		left: '10dp',
		right: '10dp',
		height: Ti.UI.SIZE,
	},
	userListSearchField:{
		top: '0dp',
		textAlign:'left',
		width: '100%',
		height: '35dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_SEND,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
//        touchEnabled: false,
	},

// winCommentList -------------------------------------------------------
	commentListWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'commentListWin',
		prevWin : null,
	},

	commentListTitleView:{
		layout: 'absolute',
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},

	commentListTitleLabel:{
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'コメント', 
	},

	commentListTableView:{ 
		top: '10dp',
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		data: [],
	},
	commentListUserTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		touchEnabled: false,
	},
	commentListNextTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		touchEnabled: false,
	},
	commentListUserListView:{
		layout: 'vertical',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	commentListUserView:{
		top: '0dp',
		bottom: '1dp',
		width: '284dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		// カスタムプロパティ
		objectName: 'commentListUserView',
		commentData: null,
		deleteButton: null,
	},
	commentListIconImage:{
		top: '4dp',
		bottom: '4dp',
		left: '4dp',
		width: '48dp',
		height: '48dp',
		defaultImage: '',
		backgroundColor: 'black',
		// カスタムプロパティ
		objectName: 'commentListIconImage',
		commentData: null,
	},
	commentListTextLabel:{
		left: '65dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		// カスタムプロパティ
		objectName: 'commentListTextLabel',
	},
/*
	commentListDeleteButton:{
		right: '15dp',		
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		title: '削除',
		visible: false,
	},
*/
	commentListDeleteButton:{
		right: '15dp',
		width: '40dp',
		height: '22dp',
		style: Ti.UI.iPhone.SystemButtonStyle.PLAIN,
		// iOSではbackgroundSelectedColorが対応していない
//		backgroundSelectedColor: 'blue',
		backgroundColor: '#CD5C5C',
		borderColor: '#000',
		borderWidth: 0.5,
		borderRadius: 5,
		font: {fontSize:12, fontFamily:'Helvetica Neue',fontWeight:'bold'},
		color: 'white',
		title: '削除',
		visible: false,
	},
	commentListDeleteButtonLabel:{
		right: '5dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: '削除',
	},

	commentListNextView:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: '40dp',
		backgroundColor: '#dedede',
	},
	commentListNextButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		title: '続きを読む',
	},
	commentListNoDataLabel:{
		top: '5dp',
		width: '90dp',
		height: '15dp',
		backgroundColor: '#dedede',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: 'データがありません',
	},


// winMydog -------------------------------------------------------
	mydogWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'mydogWin',
	},
	mydogTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'うちのわんこ', 
	},

	mydogCalendarButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		title: 'カレンダー',
	},

	mydogCameraButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		title: 'カメラ',
		systemButton:Titanium.UI.iPhone.SystemButton.CAMERA,
	},

	mydogTableView:{ 
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		data: [],
	},
	mydogArticleTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	mydogArticleSlideView:{
		layout: 'horizontal',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	mydogArticleView:{
		layout: 'vertical',
		top: '10dp',
	    bottom: '5dp',
		width: '224dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	mydogPhotoImage:{
		top: '10dp',
		width: '200dp',
		height: '200dp',
		defaultImage: '',
		backgroundColor: 'black',
		// カスタムプロパティ
		articleData: null,
	},
	mydogTextLabel:{
		top: '10dp',
	    bottom: '8dp',
		width: '200dp',
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},


// winCalendar -------------------------------------------------------
	calendarWin:{
		backgroundColor : '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'calendarWin',
	},
	calendarTitleView:{
		layout: 'absolute',
		left: '0dp',
		width: '276dp',
		height: Ti.UI.SIZE,
	},
	calendarTitleLabel:{
		top: '0dp',
		left: '0dp',
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	calendarPrevImage:{
		top : '0dp',
		right: '47dp',
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_left.png',
	},
	calendarNextImage:{
		top : '0dp',
		right: '17dp',
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_right.png',
	},

	calendarCalView:{
		layout : 'vertical',
		top : '0dp',
//		width : Ti.Platform.displayCaps.platformWidth + 'dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor : '#dedede',
	},
	calendarTableView:{
		top: '0dp',
		left: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		backgroundColor: 'white',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		data: [],
//		visible: false,
	},
	calendarTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
	},

	calendarHeaderView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '1dp',
		left: '3dp',
		right: '2dp',
//		width : Ti.Platform.displayCaps.platformWidth + 'dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	calendarHeaderLabel:{
		top : '0dp',
		right : '1dp',
		width : '44dp',
		height : '20dp',
		backgroundColor: 'white',
		text : null,
		textAlign : 'center',
		font : {fontSize:11, fontWeight:'bold'},
		color : '#3a4756'
	},

	calendarBodyView:{
		layout: 'horizontal',
		top: '0dp',
		left: '3dp',
		right: '2dp',
//		width : Ti.Platform.displayCaps.platformWidth + 'dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	calendarDayView:{
		top : '0dp',
		bottom : '1dp',
		right : '1dp',
		width : '44dp',
		height : '49dp',
//		backgroundColor : null,
//		borderColor : '#FFDCDCDF',
		// カスタムプロパティ
		objectName : 'calendarDayView',
		dayImage: null,
		dayLabel: null,
		year : null,
		month : null,
		day : null,
		current : null,
		articleData : null,
	},
	calendarDayImage:{
		top : '0dp',
		width : '100%',
		defaultImage: '',
		backgroundColor: 'black',
		image : null,
		// カスタムプロパティ
		objectName : 'calendarDayImage',
	},
	calendarDayLabel:{
		bottom : '1dp',
		left : '4dp',
		font : {fontSize:11, fontWeight:'bold'},
		color : null,
		text : null,
		// カスタムプロパティ
		objectName : 'calendarDayLabel',
	},
	calendarTodayView:{
		bottom: '0dp',
		left: '0dp',
		width: '3dp',
		height: '16dp',
		backgroundColor : '#87CEFA',
	},


// winCamera -------------------------------------------------------
	cameraWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'cameraWin',
	},
	cameraTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'カメラ', 
	},

	cameraOverlayView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	cameraFrameView:{
//		top: '100dp',
//		width: Ti.Platform.displayCaps.platformWidth + 'dp',
//		height: (Ti.Platform.displayCaps.platformWidth * 3 / 4) + 'dp',
        borderColor: 'red',
        borderWidth: 1,
	},
	cameraArticleScrollView:{
		top: '0dp',
//		width: Ti.Platform.displayCaps.platformWidth,
//		height: Ti.Platform.displayCaps.platformWidth * 3 / 4,
//		contentWidth:'auto',
		contentWidth:Ti.Platform.displayCaps.platformWidth,
		contentHeight:'auto',
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		maxZoomScale:50,
		minZoomScale:1,
		backgroundColor: '#dedede',
	},
	cameraArticleImage:{
//		top : '0dp',
//		left: '0dp',
		defaultImage: '',
		image : null,
	},
/*
	cameraSpaceView:{
		top: Ti.Platform.displayCaps.platformWidth * 3 / 4,
		width: Ti.Platform.displayCaps.platformWidth,
		height: '100%',
		backgroundColor: 'white',
	},
*/

// winCameraPost -------------------------------------------------------
	cameraPostWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'cameraPostWin',
	},
	cameraPostTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'カメラ', 
	},

	cameraPostScrollView:{
		layout: 'vertical',
		top:0,
		contentWidth:'auto',
		contentHeight:'auto',
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		backgroundColor: '#dedede',
	},
	cameraPostView:{
		layout : 'vertical',
		top : '10dp',
//		width : '284dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},

	cameraPostIconView:{
		top: '20dp',
/*
		width: '54dp',
		height: '54dp',
		borderRadius: '27dp',
*/
		width: '108dp',
		height: '108dp',
		borderRadius: '54dp',
	},
	cameraPostIconImage:{
//		width: '54dp',
//		height: '54dp',
		width: '108dp',
		height: '108dp',
		defaultImage: '',
	},

	cameraPostImage:{
		top : '10dp',
		bottom : '5dp',
		left: '10dp',
		right: '10dp',
		width: '264dp',
		height: Ti.UI.SIZE,
		defaultImage: '',
		backgroundColor: 'black',
	},
	cameraPostTextArea:{
		top : '0dp',
		bottom : '5dp',
		left: '10dp',
		width: '264dp',
		height : '90dp',
		backgroundColor: 'white',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
		// hintTextはiOSで対応されていないので、focus/blur時に処理
		hintText: 'コメントを入力してください',
		value: 'コメントを入力してください',
		suppressReturn: false,
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
	},
	
// winDiary -------------------------------------------------------
	diaryWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'diaryWin',
		nextWin: null,
	},
	diaryTitleView:{
		layout: 'absolute',
//		top: '0dp',
//		left: '0dp',
		width: '276dp',
		height: Ti.UI.SIZE,
//		backgroundColor: 'yellow',
	},
	diaryTitleLabel:{
		top: '0dp',
		left: '0dp',
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	diaryPrevImage:{
		top : '0dp',
		right: '30dp',
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_left.png',
	},
	diaryNextImage:{
		top : '0dp',
		right: '0dp',
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_right.png',
	},

	diaryTableView:{
		top: '1dp',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		left: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		data: [],
		visible: false,
	},
	diaryTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		// カスタムプロパティ
		diaryData: null,
	},

	diaryDayView:{
		top: '0dp',
		bottom: '1dp',
		width: '100%',
		height: '44dp',
		backgroundColor : 'white',
	},
	diaryDayLabel:{
		top: '5dp',
		left: '8dp',
		width: '30dp',
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:17, fontWeight:'bold'},
		color: '#3a4756',
	},
	diaryWeekdayLabel:{
		top: '25dp',
		left: '8dp',
		width: '30dp',
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:11, fontWeight:'bold'},
	},
	diaryTodayView:{
		top: '0dp',
		left: '0dp',
		width: '7dp',
		height: '100%',
		backgroundColor : '#87CEFA',
	},
	diaryStampView:{
		layout : 'horizontal',
		left: '45dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	diaryStampImage:{
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
	},
	diaryArrowImage:{
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : 'images/icon/diary_arrow.png',
	},
	diaryPhotoImage:{
		top: '6dp',
		right: '8dp',
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : 'images/icon/stamp_camera.png',
		// カスタムプロパティ
		articleData: null,
		objectName : 'diaryPhotoImage',
	},

// winTime -------------------------------------------------------
	timeWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'timeWin',
		prevWin : null,
//		openFlag : false,
	},
	timeTitleView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},

	timeTitleLabel:{
		width: Ti.UI.SIZE,
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
/*
	timeTitleTabbedBar:{
		width: '130dp',
		height: '30dp',
		backgroundColor: '#b6b6b6',
		style: Titanium.UI.iPhone.SystemButtonStyle.BAR,
	    labels: ['Month', 'Day'],
	    index: 1,
	},
*/
	timeBackButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage: 'images/icon/w_arrow_up.png',
	},
	timeListButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage: 'images/icon/titlebar.png',
		// カスタムプロパティ
		listFlag : false,
	},
	timeListImage:{
		width: '28dp',
		height: '28dp',
		defaultImage: '',
		image: 'images/icon/w_arrow_listup.png',
	},

	timeTableView:{
		top: '1dp',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		left: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		data: [],
		visible: false,
	},
	timeTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		// カスタムプロパティ
		timeData: null,
	},

	timeHourView:{
		top: '0dp',
		bottom: '1dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor : 'white',
	},
	timeHourLabel:{
		top: '0dp',
		left: '8dp',
		width: '34dp',
		height: '44dp',
		textAlign: 'right',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
	},
	timeTodayView:{
		top: '0dp',
		left: '0dp',
		width: '7dp',
		// heigth100%指定だと実機でサイズが最大になるため、最小サイズで登録数によって拡張
		height: '44dp',
		backgroundColor : '#87CEFA',
	},
	timeStampListView:{
		layout: 'vertical',
		top: '0dp',
		bottom: '6dp',
		left: '47dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	timeStampView:{
		top: '6dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		// カスタムプロパティ
		stampData : null,
		objectName : 'timeStampView',
	},
	timeStampImage:{
		top: '0dp',
		left: '0dp',
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
		touchEnabled: false,
	},
	timeStampLabel:{
		left: '36dp',
		width: '195dp',
		height: Ti.UI.SIZE,
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		touchEnabled: false,
	},
	timePlusImage:{
		top: '8dp',
		right: '8dp',
		width : '28dp',
		height : '28dp',
		defaultImage: '',
		image : 'images/icon/diary_plus.png',
	},

// winFriends -------------------------------------------------------
	friendsWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		title: 'わんとも',
		// カスタムプロパティ
		objectName : 'friendsWin',
	},
	friendsSearchButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_friends_search.png',
	},

	friendsUpdateButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		title: '更新する',
	},

	friendsTableView:{ 
		// 下のタブで表示されない余白分
		bottom: '44dp',
//		backgroundColor: '#dedede',
		backgroundColor: 'white',
		separatorColor: 'transparent',
		data: [],
	},
	friendsArticleTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	friendsDateView:{
		top: '0dp',
		width: '100%',
		height: '30dp',
		backgroundColor: '#eeeeee',
	},
	friendsDateLabel:{
		left: '10dp',
//		font: {fontSize:15, fontWeight:'bold'},
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

	friendsArticleListView:{
		layout: 'vertical',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	friendsArticleView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '1dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		// カスタムプロパティ
		articleData: null,
	},
	friendsUserIconView:{
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		width: '54dp',
		height: '54dp',
		borderRadius: '27dp',
		touchEnabled: false,
	},
	friendsUserIconImage:{
		width: '54dp',
		height: '54dp',
		defaultImage: '',
		touchEnabled: false,
	},
	friendsTextView:{
		layout: 'vertical',
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		right: '10dp',
		// friendsUserIconImageの幅(10+55)と余白（10+10）を除いたサイズ
		width: (Ti.Platform.displayCaps.platformWidth - 85) + 'dp',
		height: Ti.UI.SIZE,
		touchEnabled: false,
	},
	friendsNameView:{
		layout: 'horizontal',
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	friendsNameLabel:{
		top: '0dp',
		left: '0dp',
		right: '5dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		touchEnabled: false,
	},
	friendsUserLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
		touchEnabled: false,
	},
	friendsTextLabel:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		touchEnabled: false,
	},

	friendsTimeView:{
		top: '5dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},
	friendsTimeLabel:{
		bottom: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'right',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

	friendsCountView:{
		layout: 'horizontal',
		top: '0dp',
		right: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	friendsLikeIconImage:{
		left: '0dp',
		width: '18dp',
		height: '18dp',
		defaultImage: '',
		image: 'images/icon/b_like.png',
	},
	friendsLikeLabel:{
		left: '6dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	friendsCommentIconImage:{
		left: '12dp',
		width: '18dp',
		height: '18dp',
		defaultImage: '',
		image: 'images/icon/b_comment_square.png',
	},
	friendsCommentLabel:{
		left: '6dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	friendsPreloadImage:{
		width: '0dp',
		height: '0dp',
		visible:false
	},

	friendsNoDataTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	friendsNoDataView:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: '100%',
	},
	friendsNoDataLabel:{
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: '投稿された記事はありませんでした'
	},

// winToay -------------------------------------------------------
	todayWin:{
		backgroundColor: 'white',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		backButtonTitleImage: 'images/icon/titlebar.png',
		// タイトルバーを隠す
//		navBarHidden: true,
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'todayWin',
		prevWin : null,
	},
	todayTitleLabel:{
		width: '200dp',
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: '今日のわんこ', 
	},
	todayCalendarButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_today_calendar.png',
	},

	todayTableView:{
		top: '0dp',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		height: Ti.UI.SIZE,
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		data: [],
	},
	todayTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
	},

	todayPhotoView:{
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: (Ti.Platform.displayCaps.platformWidth * 3 / 4) + 'dp',
		backgroundColor: '#eeeeee',
	},
	todayPhotoImage:{
		top: '0dp',
//		width: Ti.Platform.displayCaps.platformWidth + 'dp',
//		height: (Ti.Platform.displayCaps.platformWidth * 3 / 4) + 'dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
		image : null,
		// カスタムプロパティ
		displayFlag: false,
	},
	todayCameraImage:{
//		width: '64dp',
//		height: '64dp',
		width: '54dp',
		height: '54dp',
		defaultImage: '',
		image: 'images/icon/b_camera.png',
	},
	todayDiaryView:{
		layout: 'horizontal',
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		// スタンプの登録が３個以下の場合、３個分＋タブで表示されない余白分
		height: (3 * 40 + 44) + 'dp',
		enabled: false,
		backgroundColor: 'white',
	},
	todayDayView:{
		layout: 'vertical',
		top: '0dp',
		width: '75dp',
		height: Ti.UI.SIZE,
		enabled: false,
		backgroundColor: 'white',
	},
	todayDayLabel:{
		top: '10dp',
		width: '100%',
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:18, fontWeight:'bold'},
		color: '#3a4756',
	},
	todayWeekdayLabel:{
		top: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:14, fontWeight:'bold'},
	},
	todayEditImage:{
		top: '3dp',
//		width: '64dp',
//		height: '64dp',
		width: '54dp',
		height: '54dp',
		defaultImage: '',
		image : 'images/icon/b_edit.png',
		backgroundColor: 'white',
	},
	todayTimeTableView:{
		top: '5dp',
		height: Ti.UI.SIZE,
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		scrollable: false,
		data: [],
	},
	todayTimeTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		// カスタムプロパティ
		timeData: null,
	},
	todayTimeStampView:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		// カスタムプロパティ
		stampData : null,
		objectName : 'todayTimeStampView',
	},
	todayTimeStampImage:{
		left: '0dp',
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
		// カスタムプロパティ
		objectName : 'todayTimeStampImage',
	},
	todayTimeStampLabel:{
		left: '36dp',
		right: '10dp',
//		width: '190dp',
		width: Ti.UI.SIZE,
		height: '40dp',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		// カスタムプロパティ
		objectName : 'todayTimeStampLabel',
	},
	
// winStamp -------------------------------------------------------
	stampWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		backButtonTitleImage: null,
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'stampWin',
		prevWin : null,
	},
	stampTitleLabel:{
		width: '200dp',
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'スタンプの選択', 
	},

	stampScrollView:{
		layout: 'vertical',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		contentWidth:'auto',
		contentHeight:'auto',
		top:0,
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		backgroundColor: '#dedede',
	},
	stampListView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '10dp',
		width: '284dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	stampView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		// カスタムプロパティ
		type : null,
	},
	stampTextLabel:{
		top: '0dp',
		width : '64dp',
		height : '32dp',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		objectName: 'stampTextLabel',
	},
	stampImage:{
		top: '0dp',
		left: '20dp',
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
		opacity : 0.3,
		// カスタムプロパティ
		index : null,
		objectName: 'stampImage',
	},
	
// winStampPost -------------------------------------------------------
	stampPostWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'stampPostWin',
		prevWin : null,
	},
	stampPostTitleLabel:{
		width: '200dp',
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	stampPostTableView:{
		top: '10dp',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		scrollable: false,
		data: [],
	},
	stampPostTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		// カスタムプロパティ
		objectName: null,
	},

	stampPostStampView:{
		width: '284dp',
		height: '52dp',
		backgroundColor: 'white',
		// カスタムプロパティ
		stampData : null,
	},
	stampPostImage:{
		left: '10dp',
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
	},
	stampPostTextLabel:{
		left: '48dp',
		width: '190dp',
		height: Ti.UI.SIZE,
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
/*
	stampPostMinusView:{
		right: '0dp',
		width: '48dp',
		height: '100%',
		// カスタムプロパティ
		objectName: 'minus',
	},
*/
	stampPostMinusImage:{
		right: '10dp',
		width : '28dp',
		height : '28dp',
		defaultImage: '',
		image : 'images/icon/diary_minus.png',
//		touchEnabled: false,
		// カスタムプロパティ
		objectName: 'minus',
	},

	stampPostListView:{
		width: '284dp',
		height: '52dp',
		backgroundColor: 'white',
		// カスタムプロパティ
		stampData : null,
	},
	stampPostListItemLabel:{
		left: '15dp',
		height: '35dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	stampPostListValueLabel:{
		right: '15dp',
		textAlign:'right',
		width: '166dp',
		height: '35dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	stampPostListValueField:{
		right: '15dp',
		textAlign:'right',
		width: '166dp',
		height: '35dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
        touchEnabled: false,
//      enabled: false,
	},
	stampPostListValueSwitch:{
		right: '15dp',
		value: false,
	},
	stampPostListPickerView:{
		bottom: '-259dp',
		height: '259dp',
	},
	stampPostListPickerToolbar:{
		top: '0dp',
		items: null,
	},
	stampPostListCancelButton:{
		style: Ti.UI.iPhone.SystemButtonStyle.BORDERED,
		title: 'Cancel',
	},
	stampPostListSpacerButton:{
		systemButton:Ti.UI.iPhone.SystemButton.FLEXIBLE_SPACE,
	},
	stampPostListDoneButton:{
		style:Ti.UI.iPhone.SystemButtonStyle.DONE,
		title: 'Done',
	},
	stampPostListDatePicker:{
		top: '43dp',
		selectionIndicator: true,
		type:Ti.UI.PICKER_TYPE_DATE,
		minDate:new Date(1980,1,1),
		maxDate:new Date(2020,12,31),
		value: null,
	},
	stampPostListHourPicker:{
		top: '43dp',
		selectionIndicator: true,
		type:Ti.UI.PICKER_TYPE_PLAIN,
		value: null,
	},

// winStampText -------------------------------------------------------
	stampTextWin:{
		backgroundColor: '#dedede',
//		barColor: '#a9a9a9',
		barImage: 'images/icon/titlebar.png',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'stampTextWin',
		prevWin : null,
	},
	stampTextTitleLabel:{
		width: '200dp',
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	stampTextDoneButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		title: '完了',
	},

	stampTextScrollView:{
		layout: 'vertical',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		contentWidth:'auto',
		contentHeight:'auto',
		top:0,
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		backgroundColor: '#dedede',
	},

	stampTextView:{
		top : '10dp',
		width : '284dp',
		height: '140dp',
		backgroundColor: 'white',
	},
	stampTextArea:{
		top : '5dp',
		left: '8dp',
		width: '268dp',
		height : '130dp',
		backgroundColor: 'white',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
		// hintTextはiOSで対応されていないので、focus/blur時に処理
		hintText: 'comment',
		value: 'comment',
		suppressReturn: false,
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
	},
	stampHistoryTableView:{ 
		top: '10dp',
		bottom: '10dp',
		width: '284dp',
		height: Ti.UI.SIZE,
//		scrollable: false,
		data: [],
	},
	stampHistoryTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		touchEnabled: false,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},
	stampHistoryView:{
		layout: 'absolute',
		top: '0dp',
		height: Ti.UI.SIZE,
	},
	stampHistoryLabel:{
		left: '15dp',
		width: '100%',
		height: '35dp',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		// カスタムプロパティ
		objectName : 'stampHistoryLabel',
	},

};

