// スタイル

exports.style = {

// common -------------------------------------------------------	
	commonSize:{
		// 計算で遣う数値なので'dp'はつけない
		screenWidth: Ti.Platform.displayCaps.platformWidth,
		screenHeight: Ti.Platform.displayCaps.platformHeight,
		// 写真がすべて表示されない場合高さを削るため、テキストの表示位置をあげる
		// 写真の高さーステータスバー(20)＋タイトルバー(44)＋カスタムタブ(44)ーメニュー(74)ースタンプ(74)
		textBottom: (Ti.Platform.displayCaps.platformWidth * 3 / 4) - (Ti.Platform.displayCaps.platformHeight - 20 - 88 - 148),
	},

	commonActivityIndicator:{
		style: Ti.UI.iPhone.ActivityIndicatorStyle.DARK,
		font: {fontSize:14, fontWeight:'bold'},
		color: 'gray',
		message: 'Loading...',
	},
	commonActivityBackView:{
		width: '100%',
		height: '100%',
		backgroundColor: 'white',
		opacity: 0.7,
	},

	commonTableHeader:{
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: '60dp',
//		backgroundColor: '#dedede',
	},	    
	commonHeaderBorder:{
	    bottom: '0dp',
		height: '0dp',
	},	    
	commonUpdateArrowImage:{
	    left: '20dp',
	    bottom: '10dp',
	    width: '23dp',
	    height: '60dp',
		defaultImage: '',
	    image:'images/whiteArrow.png',
	},
	commonPullLabel:{
	    left: '55dp', 
	    bottom: '30dp',
	    width: '200dp',
	    color:'white',
	    font: {fontSize:13, fontWeight:'bold'},
	    text: 'Pull down to refresh...',
	    textAlign: 'center',
	},
	commonLastUpdatedLabel:{
	    left: '55dp',
	    bottom: '15dp',
	    width: '200dp',
	    color: 'white',
	    font: {fontSize:12},
	    textAlign: 'center',
	},

	commonUpdateIndicator:{
	    left: '20dp',
	    bottom: '20dp',
		style: Ti.UI.iPhone.ActivityIndicatorStyle.PLAIN,
	},

	commonBackButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_arrow_left.png',
	},
	commonNextButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_arrow_right.png',
	},
	commonPlusButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_plus.png',
	},
	commonCloseButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_x.png',
	},
	
// tab -------------------------------------------------------
	tabGroupHidden:{
		tabGroupHidden: '#0f0',
		// カスタムプロパティ
	},
	tabHidden:{
		// カスタムプロパティ
	},
	tabWin:{
		bottom: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},
	tabGroupView:{
		layout: 'horizontal',
		// ステータスバー(20)＋タイトルバー(44)が座標の開始位置なので、その分とタブバーの高さを引く
//		top: (Ti.Platform.displayCaps.platformHeight - 108) + 'dp',
		bottom: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
//		backgroundColor: '#E87C8C',
		backgroundColor: '#e74c3c',
//		backgroundColor: '#d86853',
//		backgroundColor: '#48a59b',
//		backgroundColor: '#676769',
//		backgroundColor: '#ed9764',
//		backgroundColor: '#423737',
//		backgroundColor: '#6ea1c9',
//		backgroundColor: '#c67267',
//		backgroundColor: '#63768a',
//		backgroundColor: '#61594e',
	},
	tabView:{
//		layout: 'vertical',
		top: '0dp',
		left: '0dp',
//		width: '80dp',
		height: '44dp',
		// カスタムプロパティ
		objectName: null,
	},
	tabImage:{
//		top: '3dp',
//		width: '28dp',
		height: '28dp',
		defaultImage: '',
//		bubbleParent: true,
		touchEnabled: false,
		// カスタムプロパティ
		tabIndex: null,
	},
	tabLabel:{
		top: '1dp',
		width: '60dp',
		height: '10dp',
		textAlign: 'center',
		font: {fontSize:10, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: 'white',
	},

// winLogin -------------------------------------------------------
	loginWin:{
		backgroundColor: '#eeeeee',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
//		backButtonTitleImage: 'images/icon/titlebar.png',
		// タイトルバーを隠す
		navBarHidden: false,
		tabBarHidden: false,
		// カスタムプロパティ
		objectName : 'loginWin',
	},
	loginTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'ログイン', 
	},
	loginFacebookButton:{
//		top : '100dp',
	},
	loginListView:{
		layout: 'vertical',
//		top: '0dp',
		height: Ti.UI.SIZE,
	},
	loginListItemView:{
		layout: 'absolute',
		top: '1dp',
		width: '284dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		bubbleParent : false,
	},
	loginListItemLabel:{
		top: '0dp',
		left: '15dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#808080',
	},
	loginListButtonItemLabel:{
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#000',
	},
	loginListValueField:{
		top: '0dp',
		left: '15dp',
		right: '15dp',
		height: '40dp',
		textAlign:'left',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
//		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
		bubbleParent : false,
	},

// winRegist -------------------------------------------------------
	registWin:{
		backgroundColor: '#eeeeee',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
//		backButtonTitleImage: 'images/icon/titlebar.png',
		// タイトルバーを隠す
		navBarHidden: false,
		tabBarHidden: false,
		// カスタムプロパティ
		objectName : 'registWin',
	},
	registTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'ログイン', 
	},
	registListView:{
		layout: 'vertical',
//		top: '0dp',
		height: Ti.UI.SIZE,
	},
	registListItemView:{
		layout: 'absolute',
		top: '1dp',
		width: '284dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		bubbleParent : false,
	},
	registListItemLabel:{
		top: '0dp',
		left: '15dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#808080',
	},
	registListButtonItemLabel:{
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#000',
	},
	registListValueField:{
		top: '0dp',
		left: '15dp',
		right: '15dp',
		height: '40dp',
		textAlign:'left',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
//		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
		bubbleParent : false,
	},

// winPhoto -------------------------------------------------------
	photoWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		title: 'フォト',
		// カスタムプロパティ
		objectName : 'photoWin',
		prevWin : null,
	},

	photoTitleView:{
		layout: 'absolute',
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		// カスタムプロパティ
		photoTitleIconView: null,
	},
	photoTitleIconView:{
		left: '0dp',
		width: '28dp',
		height: '28dp',
//		borderRadius: '5dp',
		borderRadius: '14dp',
		backgroundColor: 'white',
		// カスタムプロパティ
		objectName : 'photoTitleIconView',
	},
	photoTitleIconImage:{
		width: '28dp',
		height: '28dp',
		defaultImage: '',
		touchEnabled: false,
	},
	photoTitleNameView:{
		layout: 'vertical',
		top: '1dp',
		left: '33dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		// カスタムプロパティ
		objectName : 'photoTitleNameView',
	},
	photoTitleNameLabel:{
//		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: '16dp',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: 'white',
		touchEnabled: false,
	},
	photoTitleUserLabel:{
//		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
//		height: '16dp',
		height: '100%',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: 'white',
		touchEnabled: false,
	},
/*
	photoTableView:{ 
		// 下のタブで表示されない余白分
		bottom: '44dp',
		backgroundColor: 'white',
		separatorColor: 'transparent',
		data: [],
	},
	photoArticleTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		touchEnabled: false,
	},

*/
	photoArticleView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '10dp',
		left: '20dp',
		right: '20dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		backgroundColor: '#dedede',
	},
	photoPhotoView:{
		top: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
//		height: (Ti.Platform.displayCaps.platformWidth * 3 / 4) + 'dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'blue',
	},
	photoPhotoImage:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
		backgroundColor: 'black',
		// カスタムプロパティ
		articleData: null,
	},
	photoArticleTextView:{
//		layout: 'horizontal',
		top: '0dp',
//		bottom: '1dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	photoTextView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '10dp',
		left: '10dp',
		right: '74dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
/*
	photoNameLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
*/
	photoTimeLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	photoTextLabel:{
		top: '5dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoLikeStampImage:{
		top: '5dp',
		bottom: '5dp',
		right: '10dp',
		width: '54dp',
		height: '54dp',
		defaultImage: '',
		image: 'images/icon/b_like_before.png',
		visible: false,
		// カスタムプロパティ
		clickFlag: false,
	},

	photoActionView:{
		layout: 'horizontal',
		top: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: '#f5f5f5',
	},
	photoCommentActionView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '1dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		backgroundColor: '#f5f5f5',
		backgroundColor: 'white',
	},
	photoCommentActionImage:{
		top: '5dp',
		bottom: '5dp',
		left: '17dp',
		width: '28dp',
		height: '28dp',
		defaultImage: '',
		image: 'images/icon/b_comment_square.png',
	},
	photoCommentActionLabel:{
		top: '5dp',
		bottom: '5dp',
		left: '5dp',
		width: Ti.UI.SIZE,
		height: '28dp',
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: 'コメントする',
		enabled: false,
	},
/*
	photoShareActionView:{
		layout: 'horizontal',
		top: '0dp',
//		right: '1dp',
		width: '199dp',
		height: Ti.UI.SIZE,
		backgroundColor: '#f5f5f5',
	},
	photoShareActionImage:{
		top: '5dp',
		bottom: '5dp',
		left: '5dp',
		width: '28dp',
		height: '28dp',
		defaultImage: '',
		image: 'images/icon/b_arrow.png',
	},
	photoShareActionLabel:{
		top: '5dp',
		bottom: '5dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: '28dp',
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: 'シェアする',
		touchEnabled: false,
	},
*/
/*
	photoCommentTableRow:{ 
		top: '0dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		touchEnabled: false,
	},
	photoCommentListView:{
		layout: 'vertical',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
	},
*/
	photoCommentFrameView:{
		top: '0dp',
	    bottom: '1dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
//		backgroundColor : '#87CEFA',
	},
	photoCommentView:{
		layout: 'horizontal',
		top: '0dp',
	    bottom: '0dp',
		left: '7dp',
		right: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	photoCommentUserIconView:{
		top: '5dp',
		bottom: '5dp',
//		left: '17dp',
		left: '10dp',
		width: '36dp',
		height: '36dp',
//		borderRadius: '5dp',
		borderRadius: '20dp',
	},
	photoCommentUserIconImage:{
		width: '40dp',
		height: '40dp',
		defaultImage: '',
	},
	photoCommentTextView:{
		layout: 'vertical',
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		right: '10dp',
		// photoCommentUserIconImage(10+36)と余白（17+10）を除いたサイズ
		width: (Ti.Platform.displayCaps.platformWidth - 73) + 'dp',
		height: Ti.UI.SIZE,
	},
	photoCommentNameView:{
		layout: 'horizontal',
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		touchEnabled: false,
	},
	photoCommentNameLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		touchEnabled: false,
	},
	photoCommentTextLabel:{
		top: '5dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		touchEnabled: false,
	},
	photoCommentTimeLabel:{
		top: '5dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
		touchEnabled: false,
	},
	photoCommentBottomView:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: '40dp',
	},

	photoCommentField:{
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		right: '10dp',
		height: '30dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
		maxLength: '60',
		hintText: 'コメントを入力する',
		keyboardToolbarColor: '#f5f5f5',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_SEND,
//        borderStyle:Ti.UI.INPUT_BORDERSTYLE_ROUNDED,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
 	},
	photoCommentPostButton:{
		width: '32dp',
		height: '28dp',
		backgroundImage: 'images/icon/titlebar.png',
	},
	photoCommentPostImage:{
		width: '18dp',
		height: '18dp',
		defaultImage: '',
		image:'images/icon/w_plus.png',
	},

	photoPhotoFullWin:{
		backgroundColor: 'black',
		tabBarHidden: true,
	},
	photoPhotoFullImage:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
		backgroundColor: 'black',
	},

	photoTableListView:{
		top: '0dp',
		left: '0dp',
		bottom: '44dp',
		backgroundColor: '#eeeeee',
		separatorStyle: Titanium.UI.iPhone.ListViewSeparatorStyle.NONE,
	},
	photoArticleList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	photoActionList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	photoCommentList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	photoCommentNextList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.GRAY,
	},
	photoCommentNextLabel:{
		top: '0dp',
		width: '100%',
		height: '50dp',
		textAlign: 'center',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

/*
	photoBottomList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
*/
	photoCommentLoadList:{
		height: Ti.UI.SIZE,
//		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.GRAY,
	},
	photoCommentLoadLabel:{
		width: '100%',
		height: '35dp',
		textAlign: 'center',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},


// winProfile -------------------------------------------------------
	profileWin:{
//		backgroundColor: '#dedede',
		backgroundColor: 'white',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		title: 'プロフィール',
		// カスタムプロパティ
		objectName : 'profileWin',
	},

	profileTitleView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	profileTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'プロフィール', 
	},

	profileEditButton:{
		left: '0dp',
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_profile_edit.png',
	},
	profileConfigButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_profile_gear.png',
	},

	profileTableView:{ 
		top: '0dp',
		// 下のタブで表示されない余白分
//		bottom: '44dp',
		width: '100%',
		height: '100%',
		backgroundColor: '#eeeeee',
//		scrollable: false,
		separatorStyle: Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		data: [],
	},
	profileInfoTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
//		touchEnabled: false,
	},
	profileInfoRowView:{
		layout: 'vertical',
		top: '0dp',
//		width: '100%',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	profileIconView:{
		top: '15dp',
		width: '90dp',
		height: '90dp',
		backgroundColor: 'white',
//		borderRadius: '8dp',
		borderRadius: '45dp',
	},
	profileIconImage:{
		width: '90dp',
		height: '90dp',
		defaultImage: '',
		touchEnabled: false,
	},
	profileInfoNameView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '10dp',
		left: '15dp',
		right: '15dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	profileInfoNameLabel:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: '18dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
	},
	profileInfoUserLabel:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: '18dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
/*
	profileFollowButton:{
		top: '0dp',
		bottom: '15dp',
		width: '95dp',
		height: '25dp',
		backgroundImage: 'images/icon/titlebar10.png',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		// ヘッダのボタンのテキストの色が反映できない
		color: '#e74c3c',
	},
*/
	profileFollowButton:{
		top: '0dp',
		bottom: '15dp',
		width: '95dp',
		height: '25dp',
		style: Ti.UI.iPhone.SystemButtonStyle.PLAIN,
		borderColor: '#dedede',
		borderWidth: 1,
//		borderRadius: 5,
		// カスタムプロパティ
		user: null,
		followFlag: false,
	},
	profileFollowButtonLabel:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#000',
		text: 'フォローする',
	},
	profileInfoBreedLabel:{
		top: '5dp',
//		left: '15dp',
//		right: '15dp',
		height: Ti.UI.SIZE,
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	profileInfoBirthLabel:{
		top: '5dp',
//		left: '15dp',
		height: Ti.UI.SIZE,
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	profileInfoMemoLabel:{
		top: '5dp',
//		left: '15dp',
//		right: '15dp',
		height: Ti.UI.SIZE,
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	profileCountTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		touchEnabled: false,
		backgroundColor: 'white',
	},
	profileCountView:{
		layout: 'horizontal',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	profileCountDataView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '10dp',
		width: '80dp',
		height: Ti.UI.SIZE,
	},
	profileCountDataLabel:{
		top: '0dp',
		height: '18dp',
		textAlign: 'center',
		font: {fontSize:16, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	profileCountDataUnitLabel:{
		top: '0dp',
		height: '18dp',
		textAlign: 'center',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

	profileArticleListView:{
		layout: 'horizontal',
		top: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: Ti.UI.SIZE,
//		backgroundColor: 'white',
	},
	profileArticleView:{
		layout: 'vertical',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	profilePhotoImage:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
		backgroundColor: 'white',
		// カスタムプロパティ
		articleData: null,
	},
	profileBottomImage:{
		top: '20dp',
		bottom: '64dp',
		width : '54dp',
		height : '54dp',
		image : 'images/icon/i_circle.png',
	},


// winProfileEdit -------------------------------------------------------
	profileEditWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		title: 'プロフィール',
		// カスタムプロパティ
		objectName : 'profileEditWin',
	},

	profileEditTitleView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	profileEditTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969',
		highlightedColor: '#696969',
		text: 'プロフィール編集', 
	},
	profileSaveButton:{
		width: '50dp',
		height: '25dp',
		backgroundImage: 'images/icon/titlebar10.png',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#e74c3c',
		title: '保存',
	},

	profileEditTableView:{ 
		top: '0dp',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		width: '100%',
		height: '100%',
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
//		scrollable: false,
		touchEnabled: false,
		data: [],
	},
	profileEditListTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		selectedBackgroundColor: 'white',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.GRAY,
		backgroundColor: '#dedede',
		touchEnabled: false,
		// カスタムプロパティ
		objectName: null,
	},
	profileEditListTitleView:{
		layout: 'absolute',
		top: '0dp',
		height: '30dp',
		backgroundColor: '#eeeeee',
	},
	profileEditListTitleLabel:{
		left: '15dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	profileEditListView:{
		layout: 'vertical',
		top: '0dp',
		height: Ti.UI.SIZE,
	},
	profileEditListItemView:{
		layout: 'absolute',
		top: '0dp',
		bottom: '1dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	profileEditListItemLabel:{
		top: '0dp',
		left: '15dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
        touchEnabled: false,
	},
	profileEditListValueLabel:{
		left: '100dp',
		right: '15dp',
		height: '35dp',
		textAlign:'right',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
        touchEnabled: false,
	},
	profileEditListValueField:{
		top: '0dp',
		left: '100dp',
		right: '15dp',
		height: '40dp',
		textAlign:'right',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
	},
	profileEditListTextArea:{
		top : '30dp',
		bottom : '10dp',
		left: '10dp',
		right: '10dp',
		height : '90dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
		// hintTextはiOSで対応されていないので、focus/blur時に処理
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
// 		touchEnabled: false,
	},

	profileEditListPickerView:{
		bottom: '-259dp',
		height: '259dp',
	},
	profileEditListPickerToolbar:{
		top: '0dp',
		items: null,
	},
	profileEditListCancelButton:{
		style: Ti.UI.iPhone.SystemButtonStyle.BORDERED,
		title: 'Cancel',
	},
	profileEditListSpacerButton:{
		systemButton:Ti.UI.iPhone.SystemButton.FLEXIBLE_SPACE,
	},
	profileEditListDoneButton:{
		style:Ti.UI.iPhone.SystemButtonStyle.DONE,
		title: 'Done',
	},
	profileEditListPicker:{
		top: '43dp',
		selectionIndicator: true,
	},
	profileEditListDatePicker:{
		top: '43dp',
		selectionIndicator: true,
		type:Ti.UI.PICKER_TYPE_DATE,
		minDate:new Date(1980,1,1),
		maxDate:new Date(2020,12,31),
		value: null,
	},

// winProfileConfig -------------------------------------------------------
	profileConfigWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		title: 'プロフィール設定',
		// カスタムプロパティ
		objectName : 'profileConfigWin',
	},

	profileConfigTitleView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	profileConfigTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'プロフィール設定', 
	},

	profileConfigTableView:{ 
		top: '0dp',
		width: '100%',
		height: '100%',
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
//		scrollable: false,
		data: [],
	},
	profileConfigListTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		selectedBackgroundColor: 'white',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		backgroundColor: '#dedede',
		// カスタムプロパティ
		objectName: null,
	},
	profileConfigListTitleView:{
		layout: 'absolute',
		top: '0dp',
		height: '30dp',
		backgroundColor: '#eeeeee',
	},
	profileConfigListTitleLabel:{
		left: '15dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	profileConfigListItemView:{
		layout: 'absolute',
		top: '0dp',
		bottom: '1dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	profileConfigListValueField:{
		top: '0dp',
		right: '15dp',
		textAlign:'right',
		width: '166dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
        touchEnabled: false,
	},
	profileConfigListItemLabel:{
		top: '0dp',
		left: '15dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	profileConfigListPickerView:{
		bottom: '-259dp',
		height: '259dp',
	},
	profileConfigListPickerToolbar:{
		top: '0dp',
		items: null,
	},
	profileConfigListCancelButton:{
		style: Ti.UI.iPhone.SystemButtonStyle.BORDERED,
		title: 'Cancel',
	},
	profileConfigListSpacerButton:{
		systemButton:Ti.UI.iPhone.SystemButton.FLEXIBLE_SPACE,
	},
	profileConfigListDoneButton:{
		style:Ti.UI.iPhone.SystemButtonStyle.DONE,
		title: 'Done',
	},
	profileConfigListHourPicker:{
		top: '43dp',
		selectionIndicator: true,
		type:Ti.UI.PICKER_TYPE_PLAIN,
		value: null,
	},

	
// winPhotoList -------------------------------------------------------
	photoListWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'photoListWin',
	},

	photoListTitleView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},

	photoListUpdateButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		title: '更新する',
	},

	photoListTodayTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: '今日のわんこ', 
	},

	photoListFirendsTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'わんとも', 
	},

	photoListPhotoTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'フォト', 
	},

	photoListLikeTitleLabel:{
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'わんポチ', 
	},

	photoListTableView:{ 
		// 下のタブで表示されない余白分
		bottom: '44dp',
//		backgroundColor: 'white',
		backgroundColor: '#eeeeee',
		separatorColor: 'transparent',
		data: [],
	},
	photoListArticleTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		touchEnabled: false,
	},
	photoListNextTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		touchEnabled: false,
	},

	photoListArticleListView:{
		layout: 'horizontal',
		top: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: Ti.UI.SIZE,
	},
	photoListArticleView:{
		layout: 'vertical',
		top: '3dp',
		left: '3dp',
//		width: '100dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		width: '106dp',
//		height: (106 * 3 / 4) + 'dp',
		backgroundColor: 'white',
	},
	photoListPhotoImage:{
//		top: '5dp',
		top: '0dp',
//		width: '90dp',
//		height: '90dp',
		// 余白(3*4)
		width: ( (Ti.Platform.displayCaps.platformWidth - 12) / 3 ) + 'dp',
//		height: (100 * 3 / 4) + 'dp',
		height: Ti.UI.SIZE,
		defaultImage: '',
		backgroundColor: 'white',
		// カスタムプロパティ
		articleData: null,
	},

	photoListFriendsArticleListView:{
		layout: 'horizontal',
		top: '0dp',
		width: '280dp',
		height: Ti.UI.SIZE,
	},
	photoListFriendsArticleView:{
		layout: 'vertical',
		top: '5dp',
		left: '10dp',
		width: '125dp',
//		height: '176dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	photoListFriendsPhotoImage:{
		top: '6dp',
		width: '113dp',
		height: '113dp',
		defaultImage: '',
		backgroundColor: 'black',
		// カスタムプロパティ
		articleData: null,
	},
	photoListFriendsNameLabel:{
		top: '3dp',
		width: '105dp',
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoListFriendsTextLabel:{
		top: '0dp',
		width: '105dp',
		height: '18dp',
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoListFriendsCountView:{
		layout: 'horizontal',
		top: '0dp',
	    bottom: '3dp',
		width: '105dp',
		height: Ti.UI.SIZE,
	},
	photoListFriendsLikeIconImage:{
		left: '0dp',
		width: '18dp',
		height: '18dp',
		defaultImage: '',
		image: 'images/icon/like.gif',
	},
	photoListFriendsLikeLabel:{
		left: '6dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	photoListFriendsCommentIconImage:{
		left: '12dp',
		width: '15dp',
		height: '15dp',
		defaultImage: '',
		image: 'images/icon/light_comment.png',
	},
	photoListFriendsCommentLabel:{
		left: '8dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:11, fontFamily:'Helvetica Neue'},
		color: '#000',
	},

	photoListNextView:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: '40dp',
		backgroundColor: '#dedede',
	},
	photoListNextButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		title: '続きを読む',
	},
	photoListNoDataLabel:{
		top: '5dp',
		width: '90dp',
		height: '15dp',
		backgroundColor: '#dedede',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: 'データがありません'
	},

	photoListFullPhotoWin:{
		backgroundColor: 'black',
	},
	photoListFullPhotoView:{
		layout : 'vertical',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		touchEnabled: false,
	},
	photoListFullPhotoImage:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
		touchEnabled: false,
	},
	photoListFullPhotoTimeLabel:{
		top: '10dp',
		left: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	photoListFullPhotoTextLabel:{
		top: '5dp',
		bottom: '15dp',
		left: '10dp',
		right: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		touchEnabled: false,
	},

// winUserList -------------------------------------------------------
	userListWin:{
		layout: 'vertical',
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'userListWin',
		prevWin : null,
	},
	userListTitleView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	userListTitleLabel:{
		width: Ti.UI.SIZE,
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},

	userListTableListView:{
		top: '0dp',
		left: '0dp',
		bottom: '44dp',
		backgroundColor: '#eeeeee',
		separatorStyle: Titanium.UI.iPhone.ListViewSeparatorStyle.NONE,
	},
	userListUserList:{
		height: Ti.UI.SIZE,
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	userListUserView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '1dp',
//		width: '284dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	userListIconView:{
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		width: '54dp',
		height: '54dp',
//		borderRadius: '10dp',
		borderRadius: '27dp',
		// カスタムプロパティ
		userData: null,
	},
	userListIconImage:{
		width: '54dp',
		height: '54dp',
		defaultImage: '',
	},
	userListNameView:{
		layout: 'vertical',
		left: '10dp',
		right: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	userListNameLabel:{
		left: '0dp',
		height: '16dp',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	userListUserLabel:{
		left: '0dp',
		height: '16dp',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

	userListSeparateView:{
		bottom: '0dp',
		width: '100%',
		height: '1dp',
		backgroundColor: '#dedede',
	},

	userListNextList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.GRAY,
	},
	userListNextLabel:{
		top: '0dp',
		width: '100%',
		height: '50dp',
		textAlign: 'center',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

	userListNoDataList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	userListNoDataView:{
		layout: 'vertical',
		top: '80dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	userListNoDataLabel:{
		textAlign: 'center',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
	},
	userListNoDataImage:{
		top: '10dp',
		width : '54dp',
		height : '54dp',
		image : 'images/icon/i_circle.png',
	},

	userListFollowButton:{
		right: '10dp',
		width: '95dp',
		height: '25dp',
		style: Ti.UI.iPhone.SystemButtonStyle.PLAIN,
		borderColor: '#dedede',
		borderWidth: 1,
//		borderRadius: 5,
		// カスタムプロパティ
		user: null,
		followFlag: false,
	},
	userListFollowButtonLabel:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#000',
		text: 'フォローする',
	},
	userListSearchTableView:{ 
		top: '0dp',
		height: Ti.UI.SIZE,
		separatorColor: 'transparent',
		data: [],
	},
	userListSearchTableRow:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		backgroundColor: '#dedede',
		touchEnabled: false,
	},
	userListSearchItemView:{
		layout: 'absolute',
		top: '0dp',
//		bottom: '1dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	userListSearchField:{
		top: '0dp',
		left: '15dp',
		right: '15dp',
		textAlign:'left',
		width: Ti.UI.SIZE,
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_SEND,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
//        touchEnabled: false,
	},

// winCommentList -------------------------------------------------------
	commentListWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'commentListWin',
		prevWin : null,
	},

	commentListTitleView:{
		layout: 'absolute',
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
	},

	commentListTitleLabel:{
		left: '0dp',
		textAlign: 'left',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'コメント', 
	},

	commentListTableView:{ 
		top: '10dp',
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		data: [],
	},
	commentListUserTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		touchEnabled: false,
	},
	commentListNextTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		touchEnabled: false,
	},
	commentListUserListView:{
		layout: 'vertical',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	commentListUserView:{
		top: '0dp',
		bottom: '1dp',
		width: '284dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		// カスタムプロパティ
		objectName: 'commentListUserView',
		commentData: null,
		deleteButton: null,
	},
	commentListIconImage:{
		top: '4dp',
		bottom: '4dp',
		left: '4dp',
		width: '48dp',
		height: '48dp',
		defaultImage: '',
		backgroundColor: 'black',
		// カスタムプロパティ
		objectName: 'commentListIconImage',
		commentData: null,
	},
	commentListTextLabel:{
		left: '65dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		// カスタムプロパティ
		objectName: 'commentListTextLabel',
	},
/*
	commentListDeleteButton:{
		right: '15dp',		
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		title: '削除',
		visible: false,
	},
*/
	commentListDeleteButton:{
		right: '15dp',
		width: '40dp',
		height: '22dp',
		style: Ti.UI.iPhone.SystemButtonStyle.PLAIN,
		// iOSではbackgroundSelectedColorが対応していない
//		backgroundSelectedColor: 'blue',
		backgroundColor: '#CD5C5C',
		borderColor: '#000',
		borderWidth: 0.5,
		borderRadius: 5,
		font: {fontSize:12, fontFamily:'Helvetica Neue',fontWeight:'bold'},
		color: 'white',
		title: '削除',
		visible: false,
	},
	commentListDeleteButtonLabel:{
		right: '5dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: '削除',
	},

	commentListNextView:{
		top: '0dp',
		left: '0dp',
		width: '100%',
		height: '40dp',
		backgroundColor: '#dedede',
	},
	commentListNextButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		title: '続きを読む',
	},
	commentListNoDataLabel:{
		top: '5dp',
		width: '90dp',
		height: '15dp',
		backgroundColor: '#dedede',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		text: 'データがありません',
	},


// winMydog -------------------------------------------------------
	mydogWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'mydogWin',
	},
	mydogTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'うちのわんこ', 
	},

	mydogCalendarButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		title: 'カレンダー',
	},

	mydogCameraButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		title: 'カメラ',
		systemButton:Titanium.UI.iPhone.SystemButton.CAMERA,
	},

	mydogTableView:{ 
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		data: [],
	},
	mydogArticleTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		touchEnabled: false,
	},
	mydogArticleSlideView:{
		layout: 'horizontal',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	mydogArticleView:{
		layout: 'vertical',
		top: '10dp',
	    bottom: '5dp',
		width: '224dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	mydogPhotoImage:{
		top: '10dp',
		width: '200dp',
		height: '200dp',
		defaultImage: '',
		backgroundColor: 'black',
		// カスタムプロパティ
		articleData: null,
	},
	mydogTextLabel:{
		top: '10dp',
	    bottom: '8dp',
		width: '200dp',
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},

// winStampList -------------------------------------------------------
	stampListWin:{
		backgroundColor : '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'calendarWin',
	},
	stampListTitleView:{
		width: '180dp',
		height: Ti.UI.SIZE,
	},
	stampListTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	stampListTableView:{
		top: '0dp',
		// 下のタブで表示されない余白分(74+44)
//		bottom: '118dp',
		left: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		data: [],
		visible: false,
//		editable: true,
		scrollable: false,
	},
	stampListTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
		// カスタムプロパティ
		stampData: null,
	},
	stampListStampGroupView:{
		top: '1dp',
		bottom: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor : 'white',
	},
	stampListStampGroupLabel:{
		top: '0dp',
		left: '14dp',
		width: '64dp',
		height: '44dp',
		textAlign: 'left',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
	},
	stampListStampListView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '3dp',
		left: '77dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	stampListStampView:{
		top: '3dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		// カスタムプロパティ
//		stampData : null,
		objectName : 'stampListStampView',
	},


// winCalendar -------------------------------------------------------
	calendarWin:{
		backgroundColor : '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'calendarWin',
	},
	calendarTitleView:{
		width: '180dp',
		height: Ti.UI.SIZE,
	},
	calendarTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	calendarPrevImage:{
		left: '0dp',
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_left.png',
	},
	calendarNextImage:{
		right: '0dp',
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_right.png',
	},

	calendarTableView:{
		top: '0dp',
//		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		width: '100%',
		height: '100%',
		backgroundColor: '#eeeeee',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		data: [],
		scrollable: false,
//		visible: false,
	},
	calendarTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		backgroundColor: '#dedede',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},

	calendarHeaderView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '1dp',
		left: '3dp',
		right: '2dp',
//		width : Ti.Platform.displayCaps.platformWidth + 'dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	calendarHeaderLabel:{
		right : '1dp',
		width : '44dp',
		height : '30dp',
//		backgroundColor: 'white',
		text : null,
		textAlign : 'center',
		font : {fontSize:12, fontWeight:'bold'},
		color : '#3a4756'
	},

	calendarBodyView:{
		layout: 'horizontal',
		top: '0dp',
		left: '3dp',
		right: '2dp',
//		width : Ti.Platform.displayCaps.platformWidth + 'dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	calendarDayView:{
		top : '5dp',
		bottom : '5dp',
		right : '1dp',
		width : '44dp',
		height : '44dp',
		borderRadius: '22dp',
		backgroundColor: 'white',
		borderColor : '#eeeeee',
		// カスタムプロパティ
		objectName : 'calendarDayView',
		dayImage: null,
		dayLabel: null,
		year : null,
		month : null,
		day : null,
		current : null,
		articleData : null,
	},
	calendarDayImage:{
//		top : '0dp',
		width : '100%',
		defaultImage: '',
		backgroundColor: 'black',
		image : null,
		// カスタムプロパティ
		objectName : 'calendarDayImage',
	},
	calendarDayLabel:{
//		bottom : '1dp',
//		left : '4dp',
		textAlign: 'center',
		font: {fontSize:16, fontFamily:'Helvetica Neue'}, 
		color : null,
		text : null,
		// カスタムプロパティ
		objectName : 'calendarDayLabel',
	},
	calendarTodayView:{
		bottom: '0dp',
		left: '0dp',
		width: '3dp',
		height: '16dp',
		backgroundColor : '#87CEFA',
	},
	calendarFullPhotoWin:{
		backgroundColor: 'black',
	},
	calendarFullPhotoView:{
		layout : 'vertical',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		touchEnabled: false,
	},
	calendarFullPhotoImage:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
		touchEnabled: false,
	},
	calendarFullPhotoTimeLabel:{
		top: '10dp',
		left: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	calendarFullPhotoTextLabel:{
		top: '5dp',
		bottom: '15dp',
		left: '10dp',
		right: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		touchEnabled: false,
	},


// winCamera -------------------------------------------------------
	cameraWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'cameraWin',
	},
	cameraTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	cameraSelectButton:{
		width: '50dp',
		height: '25dp',
		backgroundImage: 'images/icon/titlebar10.png',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#e74c3c',
	},

	cameraOverlayView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	cameraFrameView:{
//		top: '100dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: Ti.Platform.displayCaps.platformWidth + 'dp',
        borderColor: 'red',
        borderWidth: 1,
        touchEnabled: false,
	},
	cameraFrameSpaceView:{
		top: '0dp',
	},
	cameraArticleScrollView:{
		layout : 'vertical',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		contentWidth:'auto',
		contentHeight:'auto',
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		// ピンチで画像修理が難しいのでズームさせない
//		maxZoomScale:50,
//		minZoomScale:1,
		backgroundColor: '#dedede',
	},
	cameraArticleImage:{
		top : '0dp',
//		left: '0dp',
		defaultImage: '',
		image : null,
	},
/*
	cameraSpaceView:{
		top: Ti.Platform.displayCaps.platformWidth * 3 / 4,
		width: Ti.Platform.displayCaps.platformWidth,
		height: '100%',
		backgroundColor: 'white',
	},
*/

// winCameraPost -------------------------------------------------------
	cameraPostWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'cameraPostWin',
	},
	cameraPostTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	cameraPostButton:{
		width: '50dp',
		height: '25dp',
		backgroundImage: 'images/icon/titlebar10.png',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#e74c3c',
		title: '投稿',
	},

	cameraPostScrollView:{
		layout: 'vertical',
		top:0,
		contentWidth:'auto',
		contentHeight:'auto',
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		backgroundColor: '#dedede',
	},
	cameraPostView:{
		layout : 'horizontal',
		top : '0dp',
		// 下のタブで表示されない余白分＋10dp
//		bottom: '54dp',
//		width : '284dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},

	cameraPostImage:{
		top : '10dp',
		bottom : '10dp',
		left: '10dp',
		width: '94dp',
		height: Ti.UI.SIZE,
		defaultImage: '',
	},
	cameraSaveImage:{
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: Ti.UI.SIZE,
		defaultImage: '',
	},
	cameraPostTextArea:{
		top : '10dp',
		bottom : '10dp',
		left: '5dp',
		right: '10dp',
//		width: Ti.UI.SIZE,
		height : '90dp',
		backgroundColor: 'white',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: 'gray',
		maxLength: '140',
		// hintTextはiOSで対応されていないので、focus/blur時に処理
		hintText: 'コメントを入力する',
		value: 'コメントを入力する',
		suppressReturn: false,
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
	},
/*
	cameraPostIconView:{
		top : '10dp',
		bottom : '10dp',
		left: '10dp',
		width: '94dp',
		height: Ti.UI.SIZE,
		borderRadius: '47dp',
	},
	cameraPostIconImage:{
		width: '94dp',
		height: Ti.UI.SIZE,
		defaultImage: '',
	},
	cameraPostIconLabel:{
		top : '10dp',
		bottom : '10dp',
		left: '20dp',
		right: '15dp',
		width: Ti.UI.SIZE,
		height : '90dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
*/
	cameraPostIconView:{
		top: '15dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		borderRadius: '45dp',
	},
	cameraPostIconImage:{
		width: '90dp',
		height: '90dp',
		defaultImage: '',
		touchEnabled: false,
	},
	cameraPostIconNameView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '10dp',
//		left: '15dp',
//		right: '15dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	cameraPostIconNameLabel:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: '18dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
	},
	cameraPostIconUserLabel:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: '18dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	
// winDiary -------------------------------------------------------
	diaryWin:{
		backgroundColor: 'white',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'diaryWin',
		nextWin: null,
	},
	diaryTitleView:{
//		layout: 'horizontal',
		width: '180dp',
		height: Ti.UI.SIZE,
	},
	diaryTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	diaryPrevImage:{
		left: '0dp',
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_left.png',
	},
	diaryNextImage:{
		right: '0dp',
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_right.png',
	},

	diaryTableView:{
		top: '1dp',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		left: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		data: [],
//		visible: false,
	},
	diaryTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.GRAY,
		// カスタムプロパティ
		diaryData: null,
	},

	diaryDayView:{
		top: '0dp',
		bottom: '1dp',
		width: '100%',
		height: '44dp',
		backgroundColor : 'white',
	},
	diaryDayLabel:{
		top: '5dp',
		left: '8dp',
		width: '30dp',
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:17, fontWeight:'bold'},
		color: '#3a4756',
	},
	diaryWeekdayLabel:{
		top: '25dp',
		left: '8dp',
		width: '30dp',
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:11, fontWeight:'bold'},
	},
	diaryTodayView:{
		top: '0dp',
		left: '0dp',
		width: '7dp',
		height: '100%',
		backgroundColor : '#87CEFA',
	},
	diaryStampView:{
		layout : 'horizontal',
		left: '45dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	diaryStampImage:{
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
	},
	diaryArrowImage:{
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : 'images/icon/diary_arrow.png',
	},
	diaryPhotoImage:{
		top: '6dp',
		right: '8dp',
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : 'images/icon/stamp_camera.png',
		// カスタムプロパティ
		articleData: null,
		objectName : 'diaryPhotoImage',
	},

// winTime -------------------------------------------------------
	timeWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'timeWin',
		prevWin : null,
//		openFlag : false,
	},
	timeTitleView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},

	timeTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
/*
	timeTitleTabbedBar:{
		width: '130dp',
		height: '30dp',
		backgroundColor: '#b6b6b6',
		style: Titanium.UI.iPhone.SystemButtonStyle.BAR,
	    labels: ['Month', 'Day'],
	    index: 1,
	},
*/
	timeBackButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage: 'images/icon/w_arrow_up.png',
	},
	timeListButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage: 'images/icon/w_stamp_check.png',
	},

	timeTableView:{
		top: '0dp',
		// 下のタブで表示されない余白分(74+44)
		bottom: '118dp',
		left: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
//		backgroundColor: '#dedede',
		backgroundColor: '#eeeeee',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		data: [],
		visible: false,
//		editable: true,
	},
	timeTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		backgroundColor: '#dedede',
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.GRAY,
		// カスタムプロパティ
		stampData: null,
	},
	timeHourView:{
		top: '1dp',
		bottom: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor : 'white',
	},
	timeHourLabel:{
		top: '0dp',
		left: '8dp',
		width: '34dp',
		height: '44dp',
		textAlign: 'right',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
	},
	timeInsertView:{
		top: '0dp',
		left: '0dp',
		width: '7dp',
		// heigth100%指定だと実機でサイズが最大になるため、最小サイズで登録数によって拡張
		height: '44dp',
		backgroundColor : '#87CEFA',
	},
	timeOverLineView:{
		top: '0dp',
		left: '0dp',
		width: '47dp',
		height: '1dp',
		backgroundColor : 'white',
	},

	timeStampListView:{
		layout: 'vertical',
		top: '0dp',
		bottom: '3dp',
		left: '47dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	timeStampView:{
		top: '3dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		// カスタムプロパティ
//		stampData : null,
		objectName : 'timeStampView',
	},
	timeStampImage:{
		top: '3dp',
		bottom: '3dp',
		left: '0dp',
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
		touchEnabled: false,
	},
	timeStampLabel:{
		left: '36dp',
		width: '195dp',
		height: Ti.UI.SIZE,
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		touchEnabled: false,
	},
	timeMinusView:{
		top: '0dp',
		right: '0dp',
		width: '44dp',
		height: '44dp',
		// カスタムプロパティ
		objectName : 'timeMinusView',
	},
	timeMinusImage:{
		top: '8dp',
		right: '8dp',
		width : '28dp',
		height : '28dp',
		defaultImage: '',
		image : 'images/icon/diary_minus.png',
		touchEnabled: false,
	},

	timeNoDataView:{
		layout: 'vertical',
		top: '80dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	timeNoDataLabel:{
		textAlign: 'center',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
	},
	timeNoDataImage:{
		top: '10dp',
		width : '54dp',
		height : '54dp',
		image : 'images/icon/i_circle.png',
	},

	timeStampGroupTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
		// カスタムプロパティ
		stampData: null,
	},
	timeStampGroupView:{
		top: '1dp',
		bottom: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor : 'white',
	},
	timeStampGroupLabel:{
		top: '0dp',
		left: '14dp',
		width: '64dp',
		height: '44dp',
		textAlign: 'left',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
	},
	timeStampGroupListView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '3dp',
		left: '77dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	timeGroupView:{
		top: '3dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		// カスタムプロパティ
//		stampData : null,
		objectName : 'timeGroupView',
	},

	timeMenuScrollView:{
		layout: 'horizontal',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		height: '74dp',
		contentWidth:'auto',
		contentHeight:'auto',
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		scrollingEnabled: false,
		// timeWinのswipeイベントが発火しないように
		bubbleParent : false,
	},
	timeMenuFrameView:{
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: '100%',
		backgroundColor: '#dedede',
		// カスタムプロパティ
		objectName : 'timeMenuFrameView',
	},
	timeMenuListView:{
		layout: 'horizontal',
//		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		// カスタムプロパティ
		objectName : 'timeMenuListView',
	},
	timeStampSelectView:{
		top: '10dp',
		bottom: '10dp',
		left: '15dp',
		right: '15dp',
		width: '54dp',
		height: '54dp',
		borderRadius: '27dp',
		backgroundColor: 'white',
		// カスタムプロパティ
		objectName : 'timeStampSelectView',
	},
	timeStampSelectImage:{
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
		touchEnabled: false,
		// カスタムプロパティ
		objectName : 'timeStampSelectImage',
	},
	
// winFriends -------------------------------------------------------
	friendsWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'friendsWin',
		prevWin : null,
	},
	friendsTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'わんとも', 
	},
	friendsSearchButton:{
		width: '28dp',
		height: '28dp',
//		backgroundImage:'images/icon/w_friends_search.png',
		backgroundImage:'images/icon/w_friends_plus.png',
	},
	friendsCommentButtonView:{
		layout: 'horizontal',
		// コメント数の更新で位置がずれるので左から固定
		left: '16dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	friendsCommentButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_profile_comment.png',
	},
	friendsCommentCountLabel:{
		bottom: '0dp',
		left: '5dp',
		textAlign: 'left',
		font: {fontSize:16, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
	},
	friendsConfigButton:{
		width: '28dp',
		height: '28dp',
		backgroundImage:'images/icon/w_profile_gear.png',
	},

	friendsTableListView:{
		top: '0dp',
		left: '0dp',
		bottom: '44dp',
		backgroundColor: '#eeeeee',
		separatorStyle: Titanium.UI.iPhone.ListViewSeparatorStyle.NONE,
	},

	friendsDataList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	friendsDateLabel:{
		top: '0dp',
		bottom: '10dp',
		left: '0dp',
		width: '100%',
		height: '30dp',
		textAlign: 'center',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
		backgroundColor: 'white',
	},

	friendsArticleList:{
		height: Ti.UI.SIZE,
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
		backgroundColor: '#eeeeee',
	},
	friendsUnreadView:{
		top: '0dp',
		left: '0dp',
		width: '7dp',
		backgroundColor : '#87CEFA',
	},

	friendsArticleView:{
		layout: 'vertical',
		top: '0dp',
		bottom: '10dp',
		left: '20dp',
		right: '20dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		backgroundColor: '#dedede',
	},
	friendsPhotoView:{
		layout: 'vertical',
		top: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
//		height: (Ti.Platform.displayCaps.platformWidth * 3 / 4) + 'dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	friendsPhotoImage:{
//		top: '-100dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		defaultImage: '',
		backgroundColor: 'white',
		// カスタムプロパティ
		articleData: null,
	},
	friendsArticleTextView:{
//		layout: 'horizontal',
		top: '0dp',
//		bottom: '1dp',
		left: '0dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	friendsUserIconView:{
		top: '8dp',
		bottom: '8dp',
		left: '15dp',
		width: '36dp',
		height: '36dp',
		borderRadius: '18dp',
	},
	friendsUserIconImage:{
		width: '36dp',
		height: '36dp',
		defaultImage: '',
	},
	friendsTextView:{
		layout: 'vertical',
		top: '10dp',
		left: '60dp',
		right: '60dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	friendsNameLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: '16dp',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
//		color: '#696969',
		color: '#000',
	},
	friendsTextLabel:{
		top: '0dp',
		bottom: '5dp',
		left: '0dp',
//		width: Ti.UI.SIZE,
		width: '100%',
		height: '16dp',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
//		backgroundColor: 'yellow',
	},	

	friendsCountView:{
		top: '8dp',
		right: '10dp',
		width: '40dp',
		height: Ti.UI.SIZE,
	},
	friendsLikeIconImage:{
		top: '0dp',
		left: '0dp',
		width: '18dp',
		height: '18dp',
		defaultImage: '',
		image: 'images/icon/b_like.png',
	},
	friendsLikeLabel:{
		top: '1dp',
		left: '23dp',
		width: Ti.UI.SIZE,
		height: '16dp',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	friendsCommentIconImage:{
		top: '18dp',
		left: '0dp',
		width: '18dp',
		height: '18dp',
		defaultImage: '',
		image: 'images/icon/b_comment_square.png',
	},
	friendsCommentLabel:{
		top: '18dp',
		left: '23dp',
		width: Ti.UI.SIZE,
		height: '16dp',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},

	friendsNameView:{
		layout: 'horizontal',
//		top: '5dp',
		bottom: '5dp',
//		left: '76dp',
		left: '10dp',
//		right: '15dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
/*
	friendsUserLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: '16dp',
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	friendsTextLabel:{
		top: '22dp',
		bottom: '22dp',
		left: '76dp',
		right: '15dp',
		width: Ti.UI.SIZE,
		height: '34dp',
		verticalAlign: Titanium.UI.TEXT_VERTICAL_ALIGNMENT_TOP,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
	},
	friendsTimeLabel:{
		bottom: '5dp',
		left: '76dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
*/

	friendsSeparateView:{
		bottom: '0dp',
		width: '100%',
		height: '1dp',
		backgroundColor: '#dedede',
	},

	friendsNextList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
//		backgroundColor: 'white',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.GRAY,
	},
	friendsNextLabel:{
		top: '0dp',
		width: '100%',
		height: '50dp',
		textAlign: 'center',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

	friendsNoDataList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	friendsNoDataView:{
		layout: 'vertical',
//		top: '80dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	friendsNoDataLabel:{
		textAlign: 'center',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
	},
	friendsNoDataImage:{
		top: '10dp',
		width : '54dp',
		height : '54dp',
		image : 'images/icon/i_circle.png',
	},

	friendsPreloadImage:{
		width: '0dp',
		height: '0dp',
	},

// winFriendsComment -------------------------------------------------------
	friendsCommentWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'friendsCommentWin',
		prevWin : null,
	},
	friendsCommentTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'コメント', 
	},

	friendsCommentTableListView:{
		top: '0dp',
		left: '0dp',
		bottom: '44dp',
		backgroundColor: '#eeeeee',
		separatorStyle: Titanium.UI.iPhone.ListViewSeparatorStyle.NONE,
	},

	friendsCommentDataList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	friendsCommentDateLabel:{
		top: '0dp',
		left: '10dp',
		width: '100%',
		height: '30dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

	friendsCommentArticleList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	friendsCommentView:{
		layout: 'horizontal',
		top: '0dp',
	    bottom: '1dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	friendsCommentUnreadView:{
		top: '0dp',
		left: '0dp',
		width: '7dp',
		height: '64dp',
		backgroundColor : '#87CEFA',
	},
	friendsCommentUserIconView:{
		top: '5dp',
		left: '10dp',
		width: '40dp',
		height: '40dp',
//		borderRadius: '5dp',
		borderRadius: '20dp',
	},
	friendsCommentUserIconImage:{
		width: '40dp',
		height: '40dp',
		defaultImage: '',
	},
	friendsCommentTextView:{
		layout: 'vertical',
		top: '5dp',
		bottom: '5dp',
		left: '10dp',
		// unread(7)＋icon(10+40)＋text(10+x)＋photo(10+50+10)を除いたサイズ
		width: (Ti.Platform.displayCaps.platformWidth - 137) + 'dp',
		height: Ti.UI.SIZE,
	},
	friendsCommentNameView:{
		layout: 'horizontal',
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	friendsCommentNameLabel:{
		top: '0dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
//		color: '#696969',
		color: '#000',
	},
	friendsCommentTextLabel:{
		top: '5dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: '13dp',
		verticalAlign: Titanium.UI.TEXT_VERTICAL_ALIGNMENT_TOP,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	friendsCommentTimeLabel:{
		top: '5dp',
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	friendsCommentArticleView:{
		top: '7dp',
		left: '10dp',
		width: '50dp',
		height: '50dp',
	},
	friendsCommentArticleImage:{
		width: '50dp',
		height: '50dp',
		defaultImage: '',
	},	
	friendsCommentNextList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.GRAY,
	},
	friendsCommentNextLabel:{
		top: '0dp',
		width: '100%',
		height: '50dp',
		textAlign: 'center',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},

	friendsCommentNoDataList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#eeeeee',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	friendsCommentNoDataView:{
		layout: 'vertical',
		top: '80dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	friendsCommentNoDataLabel:{
		textAlign: 'center',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
	},
	friendsCommentNoDataImage:{
		top: '10dp',
		width : '54dp',
		height : '54dp',
		image : 'images/icon/i_circle.png',
	},

	friendsCommentPreloadImage:{
		width: '0dp',
		height: '0dp',
	},
	
// winFriendsConfig -------------------------------------------------------
	friendsConfigWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		title: 'わんとも設定',
		// カスタムプロパティ
		objectName : 'friendsConfigWin',
	},

	friendsConfigTitleView:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	friendsConfigTitleLabel:{
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'わんとも検索', 
	},

	friendsConfigTableView:{ 
		top: '0dp',
		width: '100%',
		height: '100%',
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
//		scrollable: false,
		data: [],
	},
	friendsConfigListTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		selectedBackgroundColor: 'white',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		backgroundColor: '#dedede',
		// カスタムプロパティ
		objectName: null,
	},
	friendsConfigListTitleView:{
		layout: 'absolute',
		top: '0dp',
		height: '30dp',
		backgroundColor: '#eeeeee',
	},
	friendsConfigListTitleLabel:{
		left: '15dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	friendsConfigListItemView:{
		layout: 'absolute',
		top: '0dp',
		bottom: '1dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	friendsConfigListValueField:{
		top: '0dp',
		left: '15dp',
		right: '15dp',
		textAlign:'left',
		width: Ti.UI.SIZE,
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
//        touchEnabled: false,
	},
	friendsConfigListItemLabel:{
		top: '0dp',
		left: '15dp',
		height: '40dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	friendsConfigListPickerView:{
		bottom: '-259dp',
		height: '259dp',
	},
	friendsConfigListPickerToolbar:{
		top: '0dp',
		items: null,
	},
	friendsConfigListCancelButton:{
		style: Ti.UI.iPhone.SystemButtonStyle.BORDERED,
		title: 'Cancel',
	},
	friendsConfigListSpacerButton:{
		systemButton:Ti.UI.iPhone.SystemButton.FLEXIBLE_SPACE,
	},
	friendsConfigListDoneButton:{
		style:Ti.UI.iPhone.SystemButtonStyle.DONE,
		title: 'Done',
	},
	friendsConfigListHourPicker:{
		top: '43dp',
		selectionIndicator: true,
		type:Ti.UI.PICKER_TYPE_PLAIN,
		value: null,
	},
	
// winToay -------------------------------------------------------
	todayWin:{
		backgroundColor: '#eeeeee',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
//		backButtonTitleImage: 'images/icon/titlebar.png',
		// タイトルバーを隠す
//		navBarHidden: true,
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'todayWin',
		prevWin : null,
	},
	todayTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: '今日のわんこ', 
	},
	todayTableView:{
		top: '0dp',
		height: Ti.UI.SIZE,
		// 下のタブで表示されない余白分(74+44)
//		bottom: '118dp',
		bottom: '44dp',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		scrollable: false,
		data: [],
		backgroundColor: 'transparent',
	},
	todayPhotoTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.Platform.displayCaps.platformWidth + 'dp',
//		backgroundColor: '#dedede',
//		backgroundColor: '#eeeeee',
//		backgroundColor: 'white',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		backgroundColor: 'transparent',
		// カスタムプロパティ
		objectName : 'todayPhotoTableRow',
	},
	todayPhotoAddTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
	},

	todayDayPhotoView:{
//		layout: 'horizontal',
		top: '0dp',
		width: '100%',
//		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		backgroundColor: 'transparent',
		// カスタムプロパティ
		objectName : 'todayDayPhotoView',
	},
	todayNoDataView:{
		layout: 'vertical',
		top: '90dp',
//		width: Ti.UI.SIZE,
		width: '100%',
		height: Ti.UI.SIZE,
//		visible: false,
	},
	todayNoDataLabel:{
		textAlign: 'center',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
	},
	todayNoDataImage:{
		top: '10dp',
		width : '54dp',
		height : '54dp',
		image : 'images/icon/i_circle.png',
		// カスタムプロパティ
		objectName : 'todayNoDataImage',
	},
	todayCameraImage:{
		top: '10dp',
		width : '54dp',
		height : '54dp',
		image : 'images/icon/b_camera.png',
		// カスタムプロパティ
		objectName : 'todayCameraImage',
	},
	todayDayWeekView:{
//		layout: 'vertical',
		top: '5dp',
		left: '10dp',
//		width: '54dp',
//		height: '54dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
//		borderRadius: '27dp',
	},
	todayDayLabel:{
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:36, fontFamily:'Adobe Gothic Std'},
		color: 'white',
	},
	todayWeekLabel:{
		top: '40dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:24, fontFamily:'Adobe Gothic Std'},
		color: 'white',
	},
/*
	todayWeekdayLabel:{
//		bottom: '7dp',
		bottom: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:14, fontWeight:'bold'},
		color: 'white',
	},
	todayCameraFrameView:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
*/

	todayPrevView:{
		top: '110dp',
		left: '0dp',
		width: '50dp',
		height: '50dp',
		// カスタムプロパティ
		objectName : 'todayPrevView',
	},
	todayPrevImage:{
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_left.png',
		touchEnabled: false,
	},
	todayNextView:{
		top: '110dp',
		right: '0dp',
		width: '50dp',
		height: '50dp',
		// カスタムプロパティ
		objectName : 'todayNextView',
	},
	todayNextImage:{
		width: '28dp',
		height: '28dp',
		image:'images/icon/w_arrow_right.png',
		touchEnabled: false,
	},

	todayPhotoScrollView:{
		layout: 'horizontal',
		// 下のタブで表示されない余白分
		top: '0dp',
		height: Ti.UI.SIZE,
		contentWidth:'auto',
		contentHeight:'auto',
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		scrollingEnabled: false,
	},

	todayPhotoTableView:{
		top: '0dp',
		height: Ti.UI.SIZE,
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		scrollable: false,
		data: [],
		backgroundColor: 'transparent',
	},

	todayPhotoFrameView:{
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
//		height: '100%',
		backgroundColor: '#dedede',
		// カスタムプロパティ
		objectName : 'todayPhotoFrameView',
	},

	todayMenuTableView:{
		height: Ti.UI.SIZE,
		// 下のタブで表示されない余白分(74+44)
		bottom: '118dp',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		backgroundColor: 'transparent',
		scrollable: false,
		data: [],
	},
	todayMenuScrollView:{
		layout: 'horizontal',
		bottom: '44dp',
		height: '74dp',
		contentWidth:'auto',
		contentHeight:'auto',
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		scrollingEnabled: false,
	},
	todayMenuFrameView:{
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: '100%',
		backgroundColor: '#dedede',
		// カスタムプロパティ
		objectName : 'todayMenuFrameView',
	},
	todayMenuListView:{
		layout: 'horizontal',
//		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		// カスタムプロパティ
		objectName : 'todayMenuListView',
	},
/*
	todayCameraView:{
		top: '10dp',
		bottom: '10dp',
		left: '15dp',
		right: '15dp',
		width: '54dp',
		height: '54dp',
		borderRadius: '27dp',
		backgroundColor: 'white',
	},
	todayCameraImage:{
		width: '54dp',
		height: '54dp',
		defaultImage: '',
		image: 'images/icon/b_camera.png',
		touchEnabled: false,
		// カスタムプロパティ
		articleData: null,
	},
	todayDayView:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	todayDayLabelView:{
		layout: 'absolute',
		top: '10dp',
		bottom: '10dp',
		left: '15dp',
		right: '15dp',
		width: '54dp',
		height: '54dp',
		borderRadius: '27dp',
		backgroundColor: 'white',
	},
	todayDayLabel:{
		top: '13dp',
		width: '100%',
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:14, fontWeight:'bold'},
		color: '#3a4756',
//		backgroundColor: 'yellow',
	},
	todayWeekdayLabel:{
		bottom: '7dp',
		width: '100%',
		height: Ti.UI.SIZE,
		textAlign: 'center',
		font : {fontSize:12, fontWeight:'bold'},
//		backgroundColor: 'blue',
	},
	todayCalendarView:{
		top: '10dp',
		bottom: '10dp',
		left: '15dp',
		right: '15dp',
		width: '54dp',
		height: '54dp',
		borderRadius: '27dp',
		backgroundColor: 'white',
	},
	todayCalendarImage:{
		width : '30dp',
		height : '30dp',
		defaultImage: '',
		image : 'images/icon/b_calendar.png',
		touchEnabled: false,
	},
*/
	todayStampSelectView:{
		top: '10dp',
		bottom: '10dp',
		left: '15dp',
		right: '15dp',
		width: '54dp',
		height: '54dp',
		borderRadius: '27dp',
		backgroundColor: 'white',
		// カスタムプロパティ
		objectName : 'todayStampSelectView',
	},
	todayStampSelectImage:{
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
		touchEnabled: false,
		// カスタムプロパティ
		objectName : 'todayStampSelectImage',
	},
	todayArticleView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '10dp',
		left: '20dp',
		right: '20dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	todayPhotoView:{
		top: '0dp',
//		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		width: Ti.UI.SIZE,
//		height: (Ti.Platform.displayCaps.platformWidth * 3 / 4) + 'dp',
		height: Ti.UI.SIZE,
	},
	todayPhotoCoverView:{
		top: '0dp',
		width: '100%',
		height: Ti.Platform.displayCaps.platformWidth + 'dp',
		backgroundColor: 'black',
		opacity: 0.05,
	},
	todayPhotoImage:{
		top: '0dp',
		width: Ti.Platform.displayCaps.platformWidth + 'dp',
		height: Ti.Platform.displayCaps.platformWidth + 'dp',
		defaultImage: '',
	},
	todayFullPhotoWin:{
		backgroundColor: 'black',
	},
	todayFullPhotoView:{
		layout : 'vertical',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		touchEnabled: false,
	},
	todayPhotoTextView:{
		layout : 'vertical',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
		touchEnabled: false,
	},
	todayPhotoTextLabel:{
		top: '10dp',
		left: '10dp',
		right: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'left',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		touchEnabled: false,
	},
	todayPhotoTimeLabel:{
		top: '0dp',
		bottom: '5dp',
		right: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		textAlign: 'right',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#696969',
	},
	todayArticleSpaceView:{
		top: '0dp',
		// タブ(44)＋メニュー(74)
		height: '118dp',
	},
	todayStampListTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
//		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.GRAY,
		// カスタムプロパティ
		stampData: null,
	},
	todayStampGroupView:{
		layout: 'horizontal',
		top: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
	},
	todayStampListView:{
		layout: 'horizontal',
		top: '1dp',
		bottom: '0dp',
//		width: '50%',
		height: Ti.UI.SIZE,
		backgroundColor : 'white',
	},
	todayStampLabel:{
		left: '10dp',
		width: '58dp',
		height: '44dp',
		textAlign: 'left',
		font : {fontSize:12, fontWeight:'bold'},
		color: '#3a4756',
		touchEnabled: false,
	},
	todayStampView:{
		left: '0dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		touchEnabled: false,
		// カスタムプロパティ
//		stampData : null,
		objectName : 'todayStampView',
	},
	todayStampImage:{
		left: '0dp',
		width : '28dp',
		height : '28dp',
		defaultImage: '',
		image : null,
		touchEnabled: false,
	},

	
// winStamp -------------------------------------------------------
	stampWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
//		backButtonTitleImage: null,
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'stampWin',
		prevWin : null,
	},
	stampTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
		text: 'スタンプ', 
	},
	stampButton:{
		width: '50dp',
		height: '25dp',
		backgroundImage: 'images/icon/titlebar10.png',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#e74c3c',
		title: '選択',
	},

	stampScrollView:{
		layout: 'vertical',
		top:0,
		// 下のタブで表示されない余白分
		bottom: '44dp',
		contentWidth:'auto',
		contentHeight:'auto',
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		backgroundColor: '#dedede',
	},
	stampListView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '10dp',
		width: '284dp',
		height: Ti.UI.SIZE,
		backgroundColor: 'white',
	},
	stampView:{
		layout: 'horizontal',
		top: '0dp',
		bottom: '10dp',
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		// カスタムプロパティ
		type : null,
	},
	stampTextLabel:{
		top: '0dp',
		width : '64dp',
		height : '32dp',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		objectName: 'stampTextLabel',
	},
	stampImage:{
		top: '0dp',
		left: '20dp',
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
		opacity : 0.3,
		// カスタムプロパティ
		index : null,
		objectName: 'stampImage',
	},
	
// winStampPost -------------------------------------------------------
	stampPostWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'stampPostWin',
		prevWin : null,
	},
	stampPostTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	stampPostButton:{
		width: '50dp',
		height: '25dp',
		backgroundImage: 'images/icon/titlebar10.png',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: '#e74c3c',
		title: '記録',
	},

	stampPostScrollView:{
		layout: 'vertical',
		top: '10dp',
		bottom: '44dp',
		contentWidth:'auto',
		contentHeight:'auto',
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		backgroundColor: '#dedede',
		visible: false,
	},

	stampPostTableView:{
//		top: '10dp',
		// 下のタブで表示されない余白分
//		bottom: '44dp',
		width: '100%',
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
		scrollable: false,
		data: [],
	},
	stampPostTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.GRAY,
//		touchEnabled: false,
		// カスタムプロパティ
		objectName: null,
	},

	stampPostStampView:{
		bottom: '1dp',
		width: '284dp',
		height: '52dp',
		backgroundColor: 'white',
		// カスタムプロパティ
		stampData : null,
	},
	stampPostImage:{
		left: '15dp',
		width : '32dp',
		height : '32dp',
		defaultImage: '',
		image : null,
	},
	stampPostTextLabel:{
		left: '55dp',
		rigth: '15dp',
		height: Ti.UI.SIZE,
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
	},

	stampPostMinusView:{
		right: '0dp',
		width: '48dp',
		height: '100%',
		// カスタムプロパティ
		objectName: 'minus',
	},
	stampPostMinusImage:{
		width : '28dp',
		height : '28dp',
		defaultImage: '',
		image : 'images/icon/diary_minus.png',
		touchEnabled: false,
	},

	stampPostListView:{
		bottom: '1dp',
		width: '284dp',
		height: '52dp',
		backgroundColor: 'white',
		// カスタムプロパティ
		stampData : null,
	},
	stampPostListItemLabel:{
		left: '15dp',
		height: '35dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	stampPostListButtonItemLabel:{
		height: '35dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue', fontWeight:'bold'},
		color: 'white',
	},
	stampPostListValueLabel:{
		right: '15dp',
		textAlign:'right',
		width: '166dp',
		height: '35dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
	},
	stampPostListValueField:{
		right: '15dp',
		textAlign:'right',
		width: '166dp',
		height: '35dp',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		hintText: '入力してください',
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
        borderStyle:Ti.UI.INPUT_BORDERSTYLE_NONE,
        touchEnabled: false,
//      enabled: false,
	},
	stampPostListValueSwitch:{
		right: '15dp',
		value: false,
	},
	stampPostListPickerView:{
		bottom: '-259dp',
		height: '259dp',
	},
	stampPostListPickerToolbar:{
		top: '0dp',
		items: null,
	},
	stampPostListCancelButton:{
		style: Ti.UI.iPhone.SystemButtonStyle.BORDERED,
		title: 'Cancel',
	},
	stampPostListSpacerButton:{
		systemButton:Ti.UI.iPhone.SystemButton.FLEXIBLE_SPACE,
	},
	stampPostListDoneButton:{
		style:Ti.UI.iPhone.SystemButtonStyle.DONE,
		title: 'Done',
	},
	stampPostListDatePicker:{
		top: '43dp',
		selectionIndicator: true,
		type:Ti.UI.PICKER_TYPE_DATE,
		minDate:new Date(1980,1,1),
		maxDate:new Date(2020,12,31),
		value: null,
	},
	stampPostListHourPicker:{
		top: '43dp',
		selectionIndicator: true,
		type:Ti.UI.PICKER_TYPE_PLAIN,
		value: null,
	},
/*
	stampPostTableListView:{
		top: '10dp',
//		left: '0dp',
		bottom: '44dp',
		width: '284dp',
		backgroundColor: '#dedede',
		separatorStyle: Titanium.UI.iPhone.ListViewSeparatorStyle.NONE,
		canScroll: false,
	},
	stampPostTextList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.GRAY,
	},
	stampPostDateList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	stampPostHourList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
	stampPostAllList:{
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Titanium.UI.iPhone.ListViewCellSelectionStyle.NONE,
	},
*/
// winStampText -------------------------------------------------------
	stampTextWin:{
		backgroundColor: '#dedede',
//		barImage: 'images/icon/titlebar.png',
		barColor: '#e74c3c',
		tabBarHidden: true,
		// カスタムプロパティ
		objectName : 'stampTextWin',
		prevWin : null,
	},
	stampTextTitleLabel:{
		textAlign: 'center',
		font: {fontSize:18, fontFamily:'Helvetica Neue', fontWeight:'bold'}, 
		color: 'white', 
		shadowOffset: {x:0,y:-1},
		shadowColor: '#696969', 
	},
	stampTextDoneButton:{
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		textAlign: 'center',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		title: '完了',
	},

	stampTextScrollView:{
		layout: 'vertical',
		// 下のタブで表示されない余白分
		bottom: '44dp',
		contentWidth:'auto',
		contentHeight:'auto',
		top:0,
		showVerticalScrollIndicator:true,
		showHorizontalScrollIndicator:true,
		backgroundColor: '#dedede',
	},

	stampTextView:{
		top : '10dp',
		width : '284dp',
		height: '140dp',
		backgroundColor: 'white',
	},
	stampTextArea:{
		top : '5dp',
		left: '10dp',
		right: '10dp',
		height : '130dp',
		backgroundColor: 'white',
		font: {fontSize:14, fontFamily:'Helvetica Neue'},
		color: '#000',
		// hintTextはiOSで対応されていないので、focus/blur時に処理
		hintText: 'comment',
		value: 'comment',
		suppressReturn: false,
        keyboardType:Ti.UI.KEYBOARD_DEFAULT,
        returnKeyType:Ti.UI.RETURNKEY_DONE,
	},
	stampHistoryTableView:{ 
		top: '10dp',
		bottom: '10dp',
		width: '284dp',
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		separatorColor: 'transparent',
		separatorStyle : Titanium.UI.iPhone.TableViewSeparatorStyle.NONE,
//		scrollable: false,
		data: [],
	},
	stampHistoryTableRow:{ 
		width: Ti.UI.SIZE,
		height: Ti.UI.SIZE,
		backgroundColor: '#dedede',
		selectionStyle: Ti.UI.iPhone.TableViewCellSelectionStyle.NONE,
		touchEnabled: false,
	},
	stampHistoryView:{
//		layout: 'horizontal',
		top: '0dp',
		bottom: '1dp',
		width: '100%',
		height: '35dp',
		backgroundColor: 'white',
	},
	stampHistoryLabel:{
		left: '15dp',
		right: '15dp',
		width: '100%',
		height: '100%',
		font: {fontSize:12, fontFamily:'Helvetica Neue'},
		color: '#000',
		// カスタムプロパティ
		objectName : 'stampHistoryLabel',
	},

};

